### ISSUE TITLE
[Bug] Blurry UI text in Chinese

### ISSUE THREAD

**Issue by JosephXmo** [WerWolv/ImHex#1029]
### Operating System

MacOS

### What's the issue you encountered?

The text of GUI looks nice when software language is set to English, but when language is set to Chinese, the text in software is very blurry like this:
<img width="111" alt="image" src="https://user-images.githubusercontent.com/34392137/231441847-55cb8b61-bd5f-442d-8b11-e6db1fdc80c4.png">

### How can the issue be reproduced?

Run ImHex, go to Help -> Settings -> Interface -> Language: Chinese (Simplified) (China)

### ImHex Version

1.28.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

DMG

**Comment by WerWolv** [comment]
Hey
The english text looks so crisp because it uses the ImGui default font which is a bitmap font. All other characters, including all chinese characters, use Unifont mainly just so ImHex can actually display all unicode characters.

I recommend you to switch to a custom font of your liking in the Font tab of the settings
