### ISSUE TITLE
[Bug] Different array sizes and wrong displaying indexes for bitfield array with "continue;"

### ISSUE THREAD

**Issue by tushkanchik239** [WerWolv/ImHex#1031]
### Operating System

Windows

### What's the issue you encountered?

When pattern is a bitfield composed of a fixed length array of other bitfields with "continue;" statement (and the first bitfield in the array satisfies "continue"-condition), in "Pattern Data" first array index is huge (maybe 2^128-1 ?). If the second bitfield in the array satisfies "continue"-condition, in "Pattern Data" first array index is 0 and the second is also 0. If I use the same array of bitfields directly (without outer bitfield), in "Pattern Data" it displays correctly, but the size of array is less than in the first case. 

![bitfield_bug2_](https://user-images.githubusercontent.com/70626668/231499064-1be2fdf6-4f66-477f-9c76-40fac43dd5a7.jpg)

![bitfield_bug2](https://user-images.githubusercontent.com/70626668/231494041-e2568326-a6ec-44e9-9d20-f5ebab50f416.jpg)

### How can the issue be reproduced?

[bitfield_bug2.txt](https://github.com/WerWolv/ImHex/files/11212848/bitfield_bug2.txt)

### ImHex Version

1.28.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by tushkanchik239** [comment]
Array index is fixed. But there is still another display problem: "Size" and "Offset" in "Pattern data" and selection in hex editor seem to display a bitfield array including bitfields excluded by "continue" statement. Should I create a new issue for this?

**Comment by WerWolv** [comment]
Hmm honestly I don't consider this a bug. `continue` simply discards an element and moves on to the next one. If you discard elements at the start and end of the array it might look like the array starts later or ends sooner but the array still always needs to start exactly where it got placed originally and end where it would have if no entries were discarded.

If you want to end the array early, you need to use `break` instead of `continue` or manually adjust the cursor to point to where you want it to point.
