### ISSUE TITLE
[Bug] Anti-aliasing does not work with CJK fonts displayed by font link

### ISSUE THREAD

**Issue by shiena** [WerWolv/ImHex#1040]
### Operating System

Windows

### What's the issue you encountered?

Anti-aliasing does not work for Japanese displayed by font link as shown below.
<img width="540" alt="image" src="https://user-images.githubusercontent.com/1295639/233381793-77da7670-aef8-444c-906d-8dc5083cdbd1.png">
Anti-aliasing works for fonts containing CJK characters like Noto CJK fonts.

### How can the issue be reproduced?

1. Change the region to Japanese from the control panel
1. Install Japanese local experience pack from Microsoft store app
1. Open form Help -> Settings -> Interface
1. Change Language to Japanese

### ImHex Version

1.28.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

scoop package

### Additional context?

about font link
https://shajisoft.com/shajisoft_wp/fontlink-for-cjk-on-english-windows-10/

**Comment by gnuhead-chieb** [comment]
フォントリンクは関係ないです。システムのフォントを取得して利用せずにプログラム内に組み込んであるUnifontという多言語用フォントを利用していることが原因で開発者はこれを変える気は無いみたいです。
https://github.com/WerWolv/ImHex/issues/420
https://github.com/WerWolv/ImHex/issues/431
https://github.com/WerWolv/ImHex/issues/1029

**Comment by WerWolv** [comment]
@gnuhead-chieb Please don't spread misinformation. I'm very much happy to improve the situation with fonts.
ImHex simply uses the ImGui font by default because I really like it. For all other characters we're using Unifont simply because it's one of the only fonts available that supports basically every single Unicode character out there.

It's also easy to change the font that's being used to another one by selecting a font file in the settings. The reason we're not using a full font selector is because it's difficult to support it on all platforms. I'm more than happy to merge any PRs adding a feature like this though.

@shiena Please try to select a different font you like in the Settings window under Fonts. Anti Aliasing should work correctly then
