### ISSUE TITLE
Can't place variables in loops?

### ISSUE THREAD

**Issue by Victor-N-Suadicani** [WerWolv/ImHex#1055]
Hi, I've tried the following to place variables in a loop. However, it doesn't seem to work. I'm wondering if I'm doing something wrong or if this is not supported and I can't find anything in the documentation about placing variables in a loop.

```
#pragma endian big

struct TableRecord {
    char tag[4];
    u32 checksum;
    u32 offset;
    u32 length;
};

struct TableDirectory {
    char tag[4];
    u16 num_tables;
    u16 search_range;
    u16 entry_selector;
    u16 range_shift;
    TableRecord table_records[num_tables];
};

TableDirectory dir @ 0x00;

for (u16 table_idx = 0, table_idx < dir.num_tables, table_idx = table_idx + 1) {
    TableRecord record = dir.table_records[table_idx];
    u8 data[record.length] @ record.offset;
}
```

The weird thing is that the pattern compiles but ImHex only shows the `dir` variable, not any of the `data` ones that are set inside the for loop.

**Comment by paxcut** [comment]
I am not sure it this is documented but one thing I find useful is the search function on discord. Here is a a quote from the author of ImHex that I found in less than a minute using loops as search word: (I hope it is ok for me to post this)
 
 ```
WerWolv 🎩 — 05/01/2023 4:24 AM
Hey, you can't use for loops because those are function statements. Instead if you need to loop over something and create new patterns, simply use an array
If you also need an index that steadily increases, you can use std::core::array_index() to get the current array index that is being processed
```
What this means is that instead of writing loops to fill arrays you define the arrays in ways that read the data  like you want to in the loop. This may seem twisted, but as you get used to it you realize that it generates more readable code and it is more powerful when you learn all the different techniques available.
It does a bit getting used to it and if I can help I'll be glad to. 
From what I gather you first read a directory that contains an array of records. The records contain offsets that you want to use as pointers to read into data. 
My suggestion, if this is correct , is to create an struct for the data arrays or simply add the data array to the table record and use the @ and $ operators to control the reading like so:
```cpp
struct TableRecord {
    char tag[4];
    u32 checksum;
    u32 offset;
    u32 length;
    s128 save = $;
    data[length] @ offset;
    $ = save;
};
```
I can't test this without data so it may not do exactly what you want. For example I'm not sure if this results on the data being displayed in the pattern results. If you can post some sample data maybe I can further look into it.

**Comment by WerWolv** [comment]
Yeah what paxcut said. You can't use loops like that and place patterns like this because it would result in multiple patterns with the same name. Instead, as loops are function statements, the placement syntax in there turns the variable into a "view". So you can use it to access values as if your type has been placed at this location but the type doesn't end up in the output.

If you really need a for loop like this, the easiest way is to create a new struct, put the types you want to place in there (using the same placement syntax you used) and then create an array of that. Or use the placement syntax in the struct directly like paxcut demonstrated. Saving and restoring the current cursor shouldn't be necessary however as placements inside of structs automatically reset the cursor back after they're done.

**Comment by paxcut** [comment]
```
 Saving and restoring the current cursor shouldn't be necessary however as placements inside of structs automatically reset the cursor back after they're done.
 ```
 I suspected as much, but I couldn't find evidence other than circumstantial until now that is. Also I couldn't remember if using @ inside structures results in data being highlighted or if you needed to create the array using some other method. Too busy to write baby tests.
