### ISSUE TITLE
[Bug] Non-Type Template Parameters and using - parse errors

### ISSUE THREAD

**Issue by piratecarrot** [WerWolv/ImHex#1068]
### Operating System

Windows

### What's the issue you encountered?

When I have a statement `using Sample`, and the `Sample` struct has a non-type template parameter, `<auto Size>`, I get an error.

```
error[P0002]: Unexpected expression
  --> <Source Code>:12:5
12 |     Sample<header.dataSize> sample[header.samples];
         ^
         Expected ';' at end of statement, got Operator (<).
```

If I move the `Sample` struct to before `ProcessData` and remove the `using Sample` statement, it works.

### How can the issue be reproduced?

My pattern data is as follows.
```
#include <type/guid.pat>

using ProcessData;

ProcessData processData @ 0x00;

using ProcessDataHeader;
using Sample;

struct ProcessData {
    ProcessDataHeader header;
    Sample<header.dataSize> sample[header.samples];
};

struct Sample<auto Size> {
    u64 timestamp [[comment("number of 100-nanoseconds elapsed since January 1, 1601 (UTC)")]];
    u8 data[Size];
};

using AnalyticsStreamHeaderFlags;

struct ProcessDataHeader {
    u8 majorVersion;
    u8 minorVersion;
    u8 headerSize;
    u8 sampleHeaderSize;
    u32 dataSize;
    u32 cycleTime [[comment("units of 100ns")]];
    AnalyticsStreamHeaderFlags completeFlags;
    type::GUID guid;
    if (majorVersion == 1 && minorVersion == 1) {
        u32 samples;
        padding[4];
        u64 streamStartTime [[comment("number of 100-nanoseconds elapsed since January 1, 1601 (UTC)")]];
        u64 streamStopTime [[comment("number of 100-nanoseconds elapsed since January 1, 1601 (UTC)")]];
    }
};

using CompressionMethod;

bitfield AnalyticsStreamHeaderFlags {
    headTimestamp : 1;
    sampleTimestamp : 1;
    dcTime : 1;
    reserved : 1;
    CompressionMethod compressionMethod : 3;
    padding : 25;
};

enum CompressionMethod : u8 {
    NONE = 0,
    RUN_LENGTH = 1,
    RESERVED = 2
};
```

### ImHex Version

1.28.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by paxcut** [comment]
The problem here seems to be that the using command is not able to deal with template patterns properly. If
using Sample<auto Size>; 
didnt throw an expected '=' error maybe the Sample  instance inside ProcessData could be identified as correct.
using Sample;
makes it look like Sample is not a template pattern which causes the error.  If the Sample variable is defined without a template value then the error changes to unspecified non-type template parameter value required.

**Comment by netthier** [comment]
Experiencing the same issue in v1.35.4

**Comment by paxcut** [comment]
What exactly is the issue you are experiencing?  

The code shown in the example above is misusing forward declarations since the structs can be reordered so that no forward declaration is needed at all, much less a non-type template forward declaration.  Forward declaration of structs is only required to allow the use of recursive definitions. A known limitation of recursive structs is that they can't be templates (not even type templates), so there should never be a need for  forward declarations of non-type struct templates and, from the looks of it, using non-type template structs in forward declarations is not even supported by the parser currently. If recursion of structs using templates is ever implemented then that should also allow the parser to deal with forward declarations but that would be a feature request, not a bug.

**Comment by netthier** [comment]
You're right, I was able to work around this by just switching the order of the structs, which worked since only one of them had templates.
I wasn't aware that recursive definitions weren't allowed for template structs, but that answers the rest of my questions, thanks.

**Comment by paxcut** [comment]
If you need the functionality of recursive template structs you can use the parent keyword instead to access parameters of the parent struct instead of passing it as a template argument.
