### ISSUE TITLE
imhex can't on Arm kali runing

### ISSUE THREAD

**Issue by zygithub-single** [WerWolv/ImHex#1072]
### What feature would you like to see?

Hope to release the arm version of imhex on kali Linux

### How will this feature be useful to you and others?

All engineers using MacBooks for penetration testing can use imhex on kali without switching systems back and forth

### Request Type

- [ ] I can provide a PoC for this feature or am willing to work on it myself and submit a PR

**Comment by WerWolv** [comment]
Hey
ImHex can be run on ARM devices but you need to compile it yourself on your local machine. More information on how to do this can be found here: https://github.com/WerWolv/ImHex/tree/master/dist/compiling

The reason there aren't any official ARM builds is because GitHub Actions simply doesn't have any runners for us to build these releases on.
If GitHub ever adds them, I'm happy to upload ARM builds as well.
