### ISSUE TITLE
[Bug] Imhex content folder in multiple dirs

### ISSUE THREAD

**Issue by sk9la** [WerWolv/ImHex#1141]
### Operating System

Linux

### What's the issue you encountered?

Hi,

Why Imhex pattern and content folder is automatically installed in /usr/local/share/imhex, /var/lib/flatpak/export/share/imhex, ~/.local/share/imhex, etc...

/usr/share/imhex is needed only, I don't understand why it's duplicated ?

### How can the issue be reproduced?

When you launch Imhex, pattern folders get ducplicated automatically to those locations

### ImHex Version

1.29.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

debian package

### Additional context?

Installed via Kali Linux: `apt install imhex imhex-patterns`

**Comment by WerWolv** [comment]
Hey

ImHex supports loading metadata from various different locations. In general it follows the XDG conventions and loads patterns and co that have been installed systemwidely from /usr/local/share. Then it also allows loading user-specific files from ~/.local/share/imhex. Lastly the flatpak folder is also considered because Flatpak adds that folder to the XDG environment variable when ImHex is run through it.

At startup, if the folders don't exist yet, ImHex will try to create them if possible so you can put the files you want in there so they are usable from within ImHex. This is intended behaviour
