### ISSUE TITLE
[Bug] First character of each line won't display when using  custom encoding.

### ISSUE THREAD

**Issue by shenlebantongying** [WerWolv/ImHex#1146]
### Operating System

Linux

### What's the issue you encountered?

First char is missing in hex editor's decoding column

### How can the issue be reproduced?

Open a file with those content, then click File -> Import -> Custom Encoding -> utf8.tbl

```
你好世界！
```

The first char `你` is not displayed.

![image](https://github.com/WerWolv/ImHex/assets/20123683/b275c5d0-2645-4f50-a3e5-e8c4a46fd3fa)

"你" is in the table at: E4BDA0

https://github.com/WerWolv/ImHex-Patterns/blob/ea225edf12927c0dd7f2c3d5bcc2323ffba82caa/encodings/utf8.tbl#LL19061C1-L19061C9

### ImHex Version

v1.29.0

### ImHex Build Type

- [x] Nightly or built from sources

### Installation type

https://aur.archlinux.org/packages/imhex-bin

### Additional context?

Changing “Bytes per line” to certain values mythically fixes the problem.

![image](https://github.com/WerWolv/ImHex/assets/20123683/9a455550-c20d-4606-a78c-5a4609247bd7)

**Comment by paxcut** [comment]
you need to turn on the display of advanced column it is a small icon shown in picture
![image](https://github.com/WerWolv/ImHex/assets/53811119/a219972c-bc49-490e-b431-63777e74eb62)

**Comment by shenlebantongying** [comment]
Thanks for taking a look :blue_heart: 

But the the nightly release build, the problem still exists:

With the default 16 bytes per line, the first char is displayed as a red dot.

![image](https://github.com/WerWolv/ImHex/assets/20123683/a164936a-578f-4e95-9cee-ac0a5e760b3c)

This is what the text supposed to looks like:

![image](https://github.com/WerWolv/ImHex/assets/20123683/d601d309-2ef5-40f9-a29b-c23c620ec03b)


[cjk.txt](https://github.com/WerWolv/ImHex/files/11794009/cjk.txt)

**Comment by paxcut** [comment]
it looks like it is selecting different ways to group the bytes depending on the number of bytes per column.  what encoding do you use to display the correct one? if i use utf-8 in the advanced decoding column it doesnt display either of the two results you see.

**Comment by paxcut** [comment]
when column of bytes is a multiple of 3 it displays the correct value otherwise it is applying the encodings incorrectly because the result should not depend on such factors.

**Comment by shenlebantongying** [comment]
The problem can be narrowed down around here:

https://github.com/WerWolv/ImHex/blob/f703b151653eecf8ab55c5fe2da22a938aae4016/plugins/builtin/source/ui/hex_editor.cpp#L131-L158

If `bytesPerRow` is 7 and every char is 3 bytes, 

When processing the 1st line, `offset` is 9 after reading 3 `getEncodingLength`.

So the `offset % bytePerRow -> 2` got pushed to `lineStartAddresses`.

When processing the 1st line, the `address` will start from 2 instead of 0 due to`address += lineStartAddresses[address / bytesPerRow];`

The displaying of other chars is just an accident (failed read will set `advance` to 1, so the address will increase 1 by 1, and eventually reach the correct ones.).

---

The lineStartAddresses in the sample below should be `[0,2,1....]`

![image](https://github.com/WerWolv/ImHex/assets/20123683/a4f3fe96-c49e-42fa-80f9-5c153c6167f5)

**Comment by paxcut** [comment]
> The lineStartAddresses in the sample below should be [0,2,1....]

I think that's what it is already, but the first value is always zero so it does not need calculation and/or storage. Seeing how it works when the number of bytes per row is a factor of three seems to indicate that the problem is likely to be that the number meant to be the line start address for the _second_ row is being applied to the _first_ row mistakenly and this causes the display of the wrong character. 

More evidence that we have found the origin of the issue can be seen from the following observation.
For encodings of size three and depending on the value of bytesPerRow there can be 0 1 or two bytes that need to be skipped because they belong to the previous line starting at the second row. As we change the value of bytesPerRow we see that either no, one or two bytes show on the first line before the first 3 byte encoding is displayed. 

I'll try to modify the code so that the first row is always processed with a line start address of zero and the calculated offsets are only used for the second, third and the rest of the rows instead of starting at the first row eliminating the problem

**Comment by shenlebantongying** [comment]
The PR I just sent fixed the problem. No more red dots, but the code needs some refinements.

Left: before fix, Right: fix.
![image](https://github.com/WerWolv/ImHex/assets/20123683/cdfe6a9a-e5df-42aa-9726-6efa7479a8f7)

test data:
```
这是一个长的句子
```
pattern for convience:
```
s24 s24_at_0x00 @ 0x00;
s24 s24_at_0x03 @ 0x03;
s24 s24_at_0x06 @ 0x06;
s24 s24_at_0x09 @ 0x09;
s24 s24_at_0x0C @ 0x0C;
s24 s24_at_0x0F @ 0x0F;
s24 s24_at_0x12 @ 0x12;
s24 s24_at_0x15 @ 0x15;
s24 s24_at_0x18 @ 0x18;
```

**Comment by paxcut** [comment]
I realize it took me too long to write the fix and I'm glad you were able to produce a working solution once you knew what the problem was. Your pr was also approved and this issue closed.

**Comment by shenlebantongying** [comment]
It took me long time to figure out too :D
