### ISSUE TITLE
[Bug] Partial/slow/lazy loading of custom encoding columns

### ISSUE THREAD

**Issue by hobohyperborian** [WerWolv/ImHex#1187]
### Operating System

Windows

### What's the issue you encountered?

If I load a custom text encoding (called a table file, a Thingie table, or a tbl file in romhacking jargon) on first loading the hex editor, the custom text encoding columns appear, but it seems to load only as a scroll down, and not at all if I Goto a specific address using the 0x prefix to that address.

If I first Goto that address and then load a custom text encoding, the custom text encoding columns don't appear at all. If I scroll up to near the start of the file, it starts to load. However it only continues loading if I Page Down or very carefully scroll up until it loads, then down until it doesn't, going back up to load if I stray too far. It does not appear at all if I Goto. 

Given that it could take 5 minutes to scroll up/down/up/down or Page Down to an address in files of this size, this behavior renders imhex unusable for finding text encoding in a non-standard fashion within roms.

Loading the custom text encoding columns doesn't appear to be affected by time, because I loaded one, Goto'd the desired addres, then ate a 20 minute lunch and it had still not displayed the custom text encoding columns when I came back.

I do not know if it exhibits this behavior if I Goto an address without a base 16 prefix to that address.

The extremely funny part is this behavior seems to only occur with for one specific game: Tactics Ogre: The Knight of Lodis (GBA). I tried loading a 70 GB PS1 rom and it displayed the custom text encoding columns perfectly when I Goto'd the same address.

### How can the issue be reproduced?

1. Download and extract the latest release of imhex as of 7/12/2023 5:30 AM Pacific Time.
2. Load your rom of "Tactics Ogre: The Knight of Lodis (GBA)" in imhex legally and temporarily extracted from a cartridge you personally own.
3. Load the table file located in this repository, making sure to first remove the *.txt file extension: https://github.com/hobohyperborian/to-tkol-text
4. Verify that the custom text encoding columns have loaded.
5. Goto addresses located between 0x6254D8 and 0x6261D0 and verify that you do not see the custom text encoding columsn loaded, nor the character names which would be in those locations if it had.
6. Scroll back up towards the top of the file until the custom text encoding columns start to appear.
7. Page Down for a few seconds to watch those columns load.
8. Scroll down until those columns stop loading, then scroll back up until they reappear, then scroll back down, then repeat the process to load some portion of those columns for the file.
9. Note that the actual text that appears there is wrong, as the address seems offset by some amount.

### ImHex Version

1.30.1 No GPU x86_64
1.30.1 x86_64
1.30.0 x86_64

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Microsoft Windows No GPU x86_64 Portable Build, with the entire set of files fully extracted from zip archive.

### Additional context?

Windows 10

I just tested two additional versions.

If you have any clue what could be causing it, please tell me what versions you think I should test.

**Comment by paxcut** [comment]
I don't have answers or workarounds but I want to provide a more reasonable way to reproduce the issue to anybody who wants to check.

Since I don't own a copy of the game I tried several files and found the issue occurs only for large files. In particular I used chm.hexpat.chm that can be found in tests>patterns>test_data folder in the imhex set of files. Once both file an encodings are loaded click in the middle of the vertical scrollbar and note the spacial encodings column is not shown. if you click back towards the top on the scrollbar the column appears again. clicking a bit further down on the scrollbar makes it disappear again.

**Comment by hobohyperborian** [comment]
Thank you @paxcut. I know none of us endorse piracy, nor do any of us partake of any rom sites, as they are illegal and I as a deeply moral person would never use, condone, or endorse piracy of games you literally cannot find anywhere else.

😉

**Comment by WerWolv** [comment]
Thanks for the report. This is indeed an issue right now.

The reason it works like this currently is because the custom encoding needs to decode the entire file from start to finish, otherwise it can't know where multi-byte characters start or end and will therefor decode them incorrectly. This decoding is currently done synchronously when the bytes are being drawn in the editor and then saved for later use. And of course it needs to have the previous line decoded already before it can decode the next line. So if you jump forward in the middle of the data, it will be missing everything inbetween and won't decode anything further

Instead, the whole thing probably needs to be done asynchronously but depending on the size of the file this will probably take quite some time. I can imagine that it will have to run 30+ minutes on a 70GB file like you're using, not sure if that's a viable option either but probably still better than what we have right now

**Comment by hobohyperborian** [comment]
> The reason it works like this currently is because the custom encoding needs to decode the entire file from start to finish, otherwise it can't know where multi-byte characters start or end and will therefor decode them incorrectly.

If the encoding or table file is a 1 byte to 1 character substitution you could skip this issue entirely with a case that handles that. 

In other cases - those you described - it may be prudent to pop or display a notification that work is being done.

---

I only ever need 1 text encoding visible, so if the extra overhead comes from decoding two text encodings then you could allow the user to specify:
1. The text column groupings present.
2. The encodings for each text column grouping.

… rather than just the visibility and encoding for the second text column grouping.

However, this feels like it would take a few weeks to prototype and bug test, so don't consider it a request or recommendation.

---

The other possible issue is that loading of custom encoded characters may be appearing in the wrong spot in the two cases I looked at. I know that the text is not where imhex + totkol.tbl is telling me it is because Cartographer (a text extraction tool) rips the text perfectly but going to the addresses specified by Cartographer does not put me at start of the text table, but at its end.

I say "possible" and "may be" because I'm still half-asleep and I'm pretty sure that the text dumped is pointer addressed so of course the addresses defined in Cartographer would be the beginnings and ends of pointer tables. I will provide an update on this after I return from Nod.

**Comment by WerWolv** [comment]
One solution for you could be to just select the region of bytes where the text is stored, right click it and select `Open selection view...`. That will pop out that region in a new tab and you can apply the custom decoding just on that.

> but I just remembered that I did not have this issue with a much older version I had installed before my most recent update a few days ago
You're right, this problem didn't exist before because ImHex just didn't care about doing it correctly and decoded every line individually. That's fast of course but inaccurate when multi-byte characters span over multiple lines

It's entirely possible that there's more bugs with this feature, I added because it was commonly requested but I rarely use it myself

**Comment by paxcut** [comment]
> I only ever need 1 text encoding visible, so if the extra overhead comes from decoding two text encodings then you could allow the user to specify:
 >  The text column groupings present (1 and 2).
  > The encodings for each text column grouping.
>… rather than just the visibility and encoding for the second text column grouping.
>However, this feels like it would take a few weeks to prototype and bug test, so don't consider it a request or recommendation.

This already exists in ImHex. If you turn off the standard encoding column (the icon before the advanced encodings column), only the advanced column is shown. At least that how it is supposed to work.

**Comment by Berylskid** [comment]
Still persists as of 4fa9586 (latest nightly build for now). Can anyone reopen it?

**Comment by paxcut** [comment]
I just tested the instructions for reproducing the issue and found no problems. 1 byte encodings should work fine and multi-byte encodings still need to start at the top but will continue until finished which didn't do at the time the issue was posted. For large files this is unavoidable and might take a while to complete but it should eventually.

**Comment by LanHikariDS** [comment]
No, this is still a problem. I have a 100MB file I'm trying to poke at with text towards the end. I shouldn't have to set something on my keyboard's Page Down key and step away for half an hour before the custom decoding actually displays where I need it.

Selection view is helpful if I know where the text is located, but I can't search the custom encoding's output to find a certain bit of text if it hasn't finished outputting

**Comment by paxcut** [comment]
you don't need to press any key at all. If the encoding is 1 byte it will start at the top of the current display. if it is multibyte, it needs to start at the top of the file and you just need to wait until it gets to the place you need. Half an hour for 100 mb means about 70k/sec which is abnormally slow.What kind of decoding is so slow? 
I don't understand the last bit about selection views and searching. using selection views means the data is small so you don't have to wait long for it to finish

**Comment by LanHikariDS** [comment]
It's Shift-JIS based, which is multibyte.

> it needs to start at the top of the file and you just need to wait until it gets to the place you need.

No, that's not how it works. On larger files, it only seems to decode if you manually scroll down to new sections. If you jump even to the first fourth of the file from the top, it won't load that part, even if you wait. As WerWolv explains-
> This decoding is currently done synchronously when the bytes are being drawn in the editor and then saved for later use. And of course it needs to have the previous line decoded already before it can decode the next line. So if you jump forward in the middle of the data, it will be missing everything inbetween and won't decode anything further

**Comment by paxcut** [comment]
It only stops decoding if you jump to an address that it hasn't gotten to yet. If you leave it at the very top of the file long enough it will eventually reach the end so there is no need to scroll manually. I tried it on chm.hexpat.chm and using shift-jis encoding it was finished in under 2 minutes.

**Comment by paxcut** [comment]
I just tested this. I loaded chm.hexpat.chm (1.3 mbs) and imported big5. Without touching the keyboard or the mouse I went to eat something. When I got back 10 minutes later I used go to to jump to the end of the file and the entire column had been decoded. 

This shows that you don't need to scroll down manually or nothing like that for the decoding to cover the entire file. There use to be a bug that prevented the decoding from progressing past a certain size regardless of the cursor location, but that got fixed and now it will move forward until it is done.. 

If you don't wait long enough and scroll to a place that hasn't been decoded yet, the decoding process will stop for as long as you remain in that location. As son as you go back to a location that has been decoded, the progress will continue automatically until it reaches the end f the file. Said progress is very slow so it may give the impression that it is not moving forward if you are constantly jumping ahead. When you do that keep track of the address that you find hasn't been decoded yet  and you'll see it is increasing little by little. 

This is the best we can do for now. Speeding it up would be a major step forward or even letting it march forward even if you get past the decoding. the information saved as it progresses is not being saved efficiently which may be making it too slow. For example it is creating an array of offsets to each line start that is stored as a 64 bit integer. Most of the entries are zero and there are many repetitions so using a run length encoding or even a huffman encoding should make it a bit faster.

Another improvement would be to only store the decodings that will be displayed instead of saving the entire file's worth as it does now.using the offsets it is fairly easy and fast to generate the decodings that are in view.

**Comment by Berylskid** [comment]
If this issue seems unsolvable even in the future, it should be closed as "not planned" (gray diagonal) instead, in my opinion. Otherwise, it should be kept opened until it gets actually solved.

**Comment by paxcut** [comment]
Which part is not solved? the custom column is not stopping anymore unless you jump ahead before it gets there. The alternative is to precompute offsets per line even though it should be faster it will still take time to finish for large files. How else could it be handled?

**Comment by LanHikariDS** [comment]
> How else could it be handled?

It could continue calculating regardless of scroll position, for one. The fact that it just stops processing it altogether if you're not at the top of the file is pretty counter-intuitive.

**Comment by paxcut** [comment]
It doesn't stop processing altogether if you are not at the top of the file. You just cannot go to a scroll position that hasn't been processed yet. The reason for this has to do with how the single byte encodings work. In that case the decoding starts at the top of the current view so for multibyte encodings the top of the current view has to already been decoded for it to continue decoding further down. That doesn't mean that it stops at the bottom of the view either, it will continue to decode until it reaches the end of the file.

It is very possible to rewrite the code so that the multibyte decodings are processed independently of the way single byte decodings do. it is just that nobody has done the actual coding to do so and without that we are stuck with the current implementation, but in all cases the amount of time you'll have to wait is the same anyways so even if it continued from any scroll positions it will still take a long time to reach the bottom for sufficiently large files. What is really needed are ways to speed up the processing and that could take a lot of work.

**Comment by LanHikariDS** [comment]
> You just cannot go to a scroll position that hasn't been processed yet.

And that's the core of the original issue, the only reason this was closed was because of the Github bot, who has no clue the actual state of the issue.

Personally, I think it could at least do with a loading bar, because there's nothing to even insinuate to the end user that the encoding process is still in progress. To an end user who isn't aware of this issue (such as myself a week ago, while still trying to learn how the custom encodings are done), it just seems like it doesn't work, and there's no way to know it's done except to jump to the bottom... which pauses the encoding process while you do so if it's not done.

**Comment by paxcut** [comment]
When the issue was posted there was a bug that prevented the decoding from proceeding past a fixed amount even if you were at the top of the file. that forced you scroll down throughout the entire file in order to decode it completely. that issue was fixed and it still works as i described. it is not ideal for sure but it is better than nothing or getting the wrong answer like it used to.  The problem is that it is too slow. if it was fast enough to let you go to any scroll location at any time then there would not be any complains. Adding a loading bar is a good idea but it would be better to have a popup window if you hover over the empty data explaining how far it has gotten and that you need to scroll up to that location to continue decoding.

**Comment by LanHikariDS** [comment]
> When the issue was posted there was a bug that prevented the decoding from proceeding past a fixed amount even if you were at the top of the file. that forced you scroll down throughout the entire file in order to decode it completely. that issue was fixed and it still works as i described.

Yeah, now that I have an Encoding file ready to actually test, this isn't true. Loading a 44MB file and sitting at the top for five minutes, even as high as 0x2CB060 isn't decoded yet if I jump downward and move up to test how far it's done.

**Comment by paxcut** [comment]
It will decode as much as you give it time to decode. It is not particularly fast  but it will move forward as soon as you stop displaying the end that hasnt been decoded yet. you can plainly see that by scrolling to the boundary, backing up one page and after a few seconds going two pages forward, you will see it got further and will continue at that pace until it finds the end. I have verfied this many times.
