### ISSUE TITLE
[Feature] Enabling builds for older macOS without objC code (i.e. normal Unix builds)

### ISSUE THREAD

**Issue by barracuda156** [WerWolv/ImHex#1203]
### What feature would you like to see?

It is not immediately clear why there is a requirement for a specific macOS version. Objective C/C++ may be indeed broken, but perhaps it can be disabled? README says that OpenGL requirement can be bypassed and software rendering fallback used in its place, if I understood correctly.

### How will this feature be useful to you and others?

There are current users of macOS 10.4–10.6, including on PowerPC machines.
I would also be interested to bring `ImHex` to Macports, provided old systems would work (with expected limitations).

### Request Type

- [ ] I can provide a PoC for this feature or am willing to work on it myself and submit a PR

### Additional context?

This is an initial inquiry; if supporting older systems is feasible in principle, I will perhaps be able to contribute on that.

**Comment by WerWolv** [comment]
Hey
The version requirement for macOS is simply for the releases that are being built. GitHub only provides us with macOS 11.0 runners which limit what kind of macOS versions we can target. Generally speaking, if you manage to compile ImHex on your own system, it will most likely run. 

ObjectiveC stuff is required for anything that interacts with the OS. This includes opening the file picker, opening websites in the default browser, detecting system settings such as theme and scaling or showing native error messages. Disabling it will require quite a few patches and probably result in a pretty sub-optimal experience. I'm not happy about using ObjC either but Apple didn't leave us much choice since they wrote basically every single system header in either ObjC or using their weird C++ extensions.

I personally think only targeting more modern versions of macOS is the right choice for ImHex as to not hold back development in order to support the few people that are still using a 15+ year old Operating System. I can't imagine it being a very pleasant experience to use ImHex without GPU acceleration on an ancient system like this. 
If you manage to make it work without having to do super invasive changes and/or disabling tons of things, I'm happy to incorporate these changes.

**Comment by barracuda156** [comment]
@WerWolv Thank you for responding!

Without trying the specific code out, my hopes for ObjC stuff even being buildable are rather low. It is very much SDK-dependent, and re-implementing some interface is likely to be a pain if at all feasible. Limited practical experience here does not inspire at all :) 
GCC does not [yet] support Blocks extension, which Apple may be using in ObjC, and overall it seems to me that ObjC support isn’t great at best. (Upstream has limited resources, and ObjC is on no one’s top list usually.)

At the same time, though with notable exceptions, larger part of modern C/C++/Fortran code builds and works on macOS fine, at least back to 10.5.

Whether it will be meaningful for practical purposes without relying on GPU is an open question. Outside of web and multimedia G5s are pretty usable, IMO. PowerBooks may be out of luck.

**Comment by barracuda156** [comment]
@WerWolv Could you say if `__int128` can be avoided? This is not about old macOS as such, FreeBSD has the same issue on two archs:
https://github.com/freebsd/freebsd-ports/blob/beba547684010d77f7b2942ae727fc6efacbf1d6/editors/imhex/Makefile#L20-L21

**Comment by WerWolv** [comment]
Hey @barracuda156, it can't be avoided but libwolv includes a software implementation of the 128 bit types. It should get enabled by default if `__uint128_t` is not available but you can manually override it too by setting the `LIBWOLV_BUILTIN_UINT128` cmake option to ON. This is used for example for the MSVC builds currently which doesn't support 128 types, even on modern platforms

**Comment by barracuda156** [comment]
@WerWolv Thank you! And one more question: can GLFW 3.1 be supported on macOS? Linux allows 3.0 apparently, but for macOS it is set to 3.2 (which is broken on older systems, while 3.1 works fine).

**Comment by WerWolv** [comment]
@barracuda156 I was following ImGui's example here, I believe newer versions of macOS don't support different OpenGL versions so you'd probably need to add a OS version check

Edit: Looks like currently macOS supports exactly OpenGL 3.2 and 4.1, nothing in-between. So if you need to lower the version, it needs to be done by checking the OS version first
