### ISSUE TITLE
[Bug] 33e9ad7@master crash

### ISSUE THREAD

**Issue by sagasm** [WerWolv/ImHex#1252]
### Operating System

Windows

### What's the issue you encountered?

imhex crash after launch

### How can the issue be reproduced?

launch imhex
.dmp file attached
[imhex.exe.8884.zip](https://github.com/WerWolv/ImHex/files/12340326/imhex.exe.8884.zip)

### ImHex Version

33e9ad7@master

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Windows Installer x86_64.zip

**Comment by iTrooz** [comment]
Hey, do you have the logs ?

**Comment by sagasm** [comment]
[logs.zip](https://github.com/WerWolv/ImHex/files/12388570/logs.zip)

**Comment by iTrooz** [comment]
Could you send a single log file, that got written when ImHex crashed, rather than the whole folder ?

Also, please provide as much context as you can. Did you get ImHex to work before ? Does the latest release (1.30.1) work ? Do you have any idea what could the problem be ?

Have you tried the NoGPU version ?

**Comment by iTrooz** [comment]
I'm going to assume this has been fixed in the latest release
