### ISSUE TITLE
[Bug] Horrible font rendering because of FXAA

### ISSUE THREAD

**Issue by RunDevelopment** [WerWolv/ImHex#1263]
### Operating System

Windows

### What's the issue you encountered?

When I first started ImHex after a fresh install, everything was blurry. Everything.

![image](https://github.com/WerWolv/ImHex/assets/20878432/bd279fe5-8af9-4602-ad3b-bce1bea14891)
![image](https://github.com/WerWolv/ImHex/assets/20878432/7087ef15-781c-4b0f-abd4-23672b986194)

Here's a comparison with a screenshot from your website.
![image](https://github.com/WerWolv/ImHex/assets/20878432/6a4a817b-83f2-4906-a829-db29b8d4fc61)

---

After having looked at the files of your application, I noticed a lot of graphics libraries I typically see in games. Combined with the custom UI and FPS limit setting I saw, I guessed that you implemented a custom renderer for the application. So the default graphics settings of my Nvidia driver probably apply.

And that was the cause of the issue. I had FXAA enabled in global settings. The fix was to disable FXAA for ImHex specifically.

I reported this a bug, because I believe that this shouldn't have been an issue in the first place.

### How can the issue be reproduced?

See above.

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by WerWolv** [comment]
Hey

I'm not sure there's much I can do about this. ImHex uses glfw to create a window and then renders everything through OpenGL using ImGui. The rendering mechanism is similar to what games use which is probably why those tools you're using wrongfully identifies ImHex as one. That's on the tool to fix though, not on us.
What do you suggest?

**Comment by WerWolv** [comment]
> It's your program that looks blurry.

That's like complaining to Microsoft that Windows runs badly after installing a virus on your computer lol


As far as I know, I have no control over what your driver does. I explicitly disabled anti aliasing in software already but it doesn't seem to honor this setting. Maybe it also just does it with OpenGL and not D3D, no idea.
I know NVidia keeps lists of games and applies "recommended" settings according to those. Since ImHex is probably not on one of them, it just applies whatever it thinks is the best.

**Comment by RunDevelopment** [comment]
> That's like complaining to Microsoft that Windows runs badly after installing a virus on your computer lol

With the minor difference that the software that messes with ImHex is the official driver of the GPU your program is using for rendering.

**Comment by WerWolv** [comment]
I played around some more and managed to reporoduce the issue by manually changing the `Adjust Image Settings` to `Use advanced 3D image settings` and then enabling the `Antialiasing - FXAA` option in the global `Manage 3D Settings` screen.

These are both advanced options (meaning if used incorrectly they will break things) and are turned off by default (the `Let the 3D application decide` and `Use my preference emphasising` don't enable it) so to me this is entirely a user / configuration error.
Non the less, I tried to force-disable FXAA in ImHex using like 5 different ways and the driver seemed to completely ignore each of those attempts. 

I truly believe you shouldn't be messing with global driver settings like that but instead enable / disable specific options per applications to avoid issues like this with ImHex or other applications in the future. Force-enabling settings likely makes things worse instead of helping. Both game and application devs usually implement these features (and often provide settings for them) in their software in ways that work best for their specific use-case.
Thanks for the report though, if in the future another person has the same issue, I will direct them here.
