### ISSUE TITLE
[fix] Removal of e-Tugra root certificate

### ISSUE THREAD

**Issue by nagaripratap** [WerWolv/ImHex#1281]
**Description**
Certifi 2023.07.22 removes root certificates from "e-Tugra" from the root store. These are in the process of being removed from Mozilla's trust store.

e-Tugra's root certificates are being removed pursuant to an investigation prompted by reporting of security issues in their systems. Conclusions of Mozilla's investigation can be found here.

**Information**

Manifest Path : [main/romfs/cacert.pem](https://github.com/WerWolv/ImHex/blob/f725d763d1443ec7f6d85e492e4c038d12a70ff8/main/romfs/cacert.pem#L1388)

**Comment by iTrooz** [comment]
Thanks for the report !

So apparently, that file was part of an old bug fix (#680), that since got scrapped, that file is a remnant of that.

Whether or not that bugfix should have been scrapped is another question, but in any case we probably won't come back to bundling the cacert file inside this repository, so I'm removing it

Thanks !

**Comment by nagaripratap** [comment]
Great, appreciate your swift response
