### ISSUE TITLE
[Bug] Ceiling in the Data Processor is broken

### ISSUE THREAD

**Issue by Nemoumbra** [WerWolv/ImHex#1294]
### Operating System

Windows

### What's the issue you encountered?

![image](https://github.com/WerWolv/ImHex/assets/62447396/55c62a78-ce8a-4511-915c-fedca3fa36d6)

The method `NodeArithmeticCeil::process()` sets an integer on output, which then gets copied into the input buffer for the display node. Literally copied (like `std::bit_cast<T>` would do)... So the display node tries to show us `03 00 00 00 00 ... 00 00 == 1.09355985956474238076e-4950`. It happens in `const long double& Node::getFloatOnInput(u32 index)` at the last line.

Either we need to use a conversion and not a copy, or the output attribute has to be made an integer.

### How can the issue be reproduced?

Create the graph as shown in the image and run the evaluator.

### ImHex Version

Self-built version (one of the latest)

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Self-built.

**Comment by Nemoumbra** [comment]
Same with floor...

**Comment by Nemoumbra** [comment]
And with round...

**Comment by paxcut** [comment]
In my opinion the bug is that the output attribute is float. As you already point out the value that is being sent to the output is an integer that has the correct value.  Another way to see that is using the graph below.
The other two operations do the same thing and I have tested many more cases and they all give the correct answer. 

![image](https://github.com/WerWolv/ImHex/assets/53811119/b0957898-5518-454b-943c-12c4dccf5e5b)


I think eventually there should be nodes that convert floats to int and vice-versa without having to use buffers in between them. From int to float the conversion is straight forward. From float to int you have to choose one of these three operations to select how you want to round. Thus it makes sense to make them be type conversions instead of just value changers.

Let me emphasize that I am not suggesting that this is the way this issue should be handled, it is just the way it appears to me.

**Comment by paxcut** [comment]
I think this is fixed. At least your test case on latest release works ok

![image](https://github.com/WerWolv/ImHex/assets/53811119/0f28ef03-710d-402c-9902-102be258a15f)

**Comment by Nemoumbra** [comment]
I'm closing this as fixed.
