### ISSUE TITLE
[Bug] Can't stop evaluation of a pattern in the preprocessor stage

### ISSUE THREAD

**Issue by Calcoph** [WerWolv/ImHex#1297]
### Operating System

Windows

### What's the issue you encountered?

I tried to run
```rust
#define ? [[comment("?")]]

struct A {
    u8 myvar;
    u8 unkownvar?;
};
```

Which I believed resulted in recursively applying the define on itself, therefore it entered in an infinite loop.

The red square button to stop the pattern evaluation doesn't work. Also, trying to close imhex doesn't work, because it says there are currently evaluating patterns. The only solution was to kill imhex via task manager.

### How can the issue be reproduced?

run
```rust
#define ? [[comment("?")]]

struct A {
    u8 myvar;
    u8 unkownvar?;
};
```

### ImHex Version

1.30.1 4e7c381

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

MSI

**Comment by jumanji144** [comment]
This is fixed, both the code running infinitely and not being able to stop in the preprocessor step

**Comment by paxcut** [comment]
That define is not valid anyway. Only valid C identifiers can be used in the define as names. So for example the following will work
```cpp
#define comment [[comment("?")]]

struct A {
    u8 myvar;
    u8 unkownvar comment;
};

A a@0
```
No recursion happens because the substitution is only executed once. The result is this
![image](https://github.com/user-attachments/assets/746e9cd8-f245-4c5c-bc0c-c605c238ed0d)
