### ISSUE TITLE
Can't put conditionals in top-level.

### ISSUE THREAD

**Issue by roblabla** [WerWolv/ImHex#130]
```c
struct Test {
    u8 data;
}

Test test @ 0;
if (test.data == 0)
    u8 test2 @ 0x04;
```

This fails with the following error: "Parser: invalid sequence".

**Comment by roblabla** [comment]
Loops also don't work.

**Comment by WerWolv** [comment]
Closing this as it's been open for so long and we mostly moved to the consensus of using some sort of top level struct that handles all the logic since the global scope acts more like a function than a type.

Here's how the same pattern could look like using that approach. (I used relative offsets now because that's usually the preferred way but placements inside of structs are possible too now)
```rust
struct Test {
    u8 data;
};

struct FileType {
  Test test;
  padding[3];
  if (test.data == 0)
    u8 test2;
};

FileType fileType @ 0x00;
```
