### ISSUE TITLE
[Feature] Add `std::core::array_address()`

### ISSUE THREAD

**Issue by bgilbert** [WerWolv/ImHex#1305]
### What feature would you like to see?

Add `std::core::array_address()`, which could be used in a pattern to get the address of the containing array.  This would work similarly to `std::core::array_index()`.

### How will this feature be useful to you and others?

Currently, if an array needs to add variable-length entries until a certain number of bytes have been consumed, the parent pattern needs to calculate the address of the end of the array and pass it in.  For example, here's a pattern that reads a two-byte length field and then reads backslash-delimited strings until the length is reached:

```
#include <std/mem.pat>

struct StringValue<auto Limit> {
    char value[while(std::mem::read_unsigned($, 1) != 92 && $ < Limit)];
    if ($ < Limit) {
        padding[1];
    } else {
        break;
    }
};

u16 length @ 0;
u32 limit = $ + length;
StringValue<limit> strs[while (true)] @ $;
```

`StringValue` needs to know the limit so it doesn't overrun the last entry.  `array_address()` would avoid needing to calculate it the top level:

```
#include <std/mem.pat>

struct StringValue<auto Length> {
    u32 limit = std::mem::array_address() + Length;
    char value[while(std::mem::read_unsigned($, 1) != 92 && $ < limit)];
    if ($ < limit) {
        padding[1];
    } else {
        break;
    }
};

u16 length @ 0;
StringValue<length> strs[while (true)] @ $;
```

### Request Type

- [ ] I can provide a PoC for this feature or am willing to work on it myself and submit a PR

**Comment by paxcut** [comment]
Before I say anything I want to apologize for the amount of time it has taken me to investigate this as it deserves to be. Also I am truly grateful for the patience you have shown. By the time you are done reading this long post you probably will be disappointed by its conclusions and understandably so. In a perfect world I would have had more time back when started to look at this and I would  not have been so distracted with other concerns.  That is not an excuse and there is no excuse for poor performance Hence the apology.

In what follows let me be clear that I am in no way trying to justify my point of view in the contention. I merely wish to explain the reasons why we see what we see and based on those reasons to deduce what must be done in order to obtain the desired results. In our previous discussions we tried to accomplish the feature you  request using the  addressof operator together with the parent key construct to obtain the address of the parent, but it didn't seem to work for some unknown reason.  The is one thing we can assume without any reservations.

```cpp
 Placing an array at an offset of the data is equivalent to taking a  pattern that holds the same array inside of it and placing it at the same offset in the data. 
```

This is self apparent truth that needs no explanation. The most and perhaps only downside of doing this insertion is the introduction of an indent in the pattern tree but that can be easily eliminated using the inline attribute. You probably are thinking now " Hey! We already tried that and you know it doesn't work!" but remember that it wasn't so much that it failed, it just wasn't providing the answer we wanted. Lets revisit the example.

We start with

```cpp
#include <std/mem.pat>
#include <std/io.pat>
struct Pat {
    std::print("{}", addressof(parent));
    char c;
};
Pat a[4] @ 0;
Pat b[4] @ 4;
```
which doesn't work  even though it seems it should. I will explain why it doesn't work when I introduce the second assumption. For now lets continue by considering 
```cpp
#include <std/mem.pat>
#include <std/io.pat>
struct Pat {
    std::print("{}", addressof(parent));
    char c;
};
struct A {
    Pat a[4];
    Pat b[4];
};
A a @ 0;
```
To see if we can use the first assumption. The second assumption was discovered when I finally was able to track down the parent of the array  elements (I posted the question on discord but no-one answered). In all its glory
```
ImHex doesn't consider the arrays that hold the elements to be the parent of said elements. 
```
As the AST is being created the variables are created and filled in the order they appear in  their patterns. When you write sizeof(parent) in a child the actual size of the array is simply not known yet. ImHex is pretty straight forward once you get to know it a bit. If it cannot do something it just doesn't, but It gets you the next best thing. In this case that would be the size of the structure holding the array which is also not known but the size it has at that moment also wont change until the entire array is read. 

It makes sense to do it this way (to me at least) and it also explains why the first code we tried gave the error it did. The arrays are global so the parent doesn't exist. It also explains why the second code we tried works but gives the same answer for all the elements of the two arrays. They all have the same parent and it sits at the origin of the data.

Furthermore we can check if the assumption is correct by using it to create a third example. We start just like that other cases with

```cpp
#include <std/mem.pat>
#include <std/io.pat>

struct Pat {
    std::print("{}", addressof(parent));
    char c;
};
```
Now instead of creating one pattern that holds the two arrays you create one pattern that represents a parent. Their size is not important. What is important here is that each child is able to identify its parent Depending on how the data is laid out you could write

```cpp
struct A4 {
    Pat a4[4];
};
```
or 

```cpp
struct A_size {
    u8 size;
    Pat a4[size];
};
```
or even
```cpp
struct AT<auto size> {
    Pat a4[size];
};
```
The rest is simply
```cpp
struct A {
    A4 a2[2]; 
};

A a @ 0;
```
with the correct names and  it produces is what we were after
```
I: 0
I: 0
I: 0
I: 0
I: 4
I: 4
I: 4
I: 4
I: Pattern exited with code: 0
I: Evaluation took 0.0073999s
```
The fact is that as it stands, ImHex already has the ability to do exactly what your request asks for. Would creating a separate function make it easier or faster to achieve the same result? Maybe so but functions  and parents don't mix well, that is to say, you cannot call a function with the parent as an argument and invoke it in the body of  a child and expect that the function will have access to the child parent in its body, By the time the code reaches the function the identity of the parent will be overridden.  The parent construct if very contextual and can only be used safely inside true children. You may pass a copy of the value and that would be  what is done if you need to perform complex calculations based on the values the parent takes.

As a way to make it up to you for taking so long to and end up not writing the function you asked for I worked a bit to make the code more streamlined and show the results in more places.
```cpp
#include <std/mem.pat>
#include <std/io.pat>


struct Pat {
    u32 array_address = addressof(parent);
    std::print("{:#x}",array_address );
    char c;
}[[format("format_pat")]];

fn format_pat(auto pat) {
    return std::format("{:#x}",pat.array_address);
};

struct A4 {
    Pat a4[4];
}[[inline]];

struct A {
    A4 a2[2]; 
}[[inline]];


A a @ 0;
```
and a picture of the result
![image](https://github.com/WerWolv/ImHex/assets/53811119/f6fd7a56-72dc-4c86-9214-7d8f722236c9)

If you want to continue the discussion lets use something more appropriate like discord.

**Comment by bgilbert** [comment]
Yeah, that's fair.  The additional struct adds an extra level of hierarchy when accessing field values from code, but perhaps that isn't a big issue.

Thanks for digging into this.
