### ISSUE TITLE
[Bug] No tff default extension when selecting a font from settings.

### ISSUE THREAD

**Issue by paxcut** [WerWolv/ImHex#1367]
### Operating System

Windows

### What's the issue you encountered?

The open file dialog shows *.otf twice but *.ttf is not among the options. The only way to select a .tff is using view all.

### How can the issue be reproduced?

1) start ImHex.
2) Click Extra>Settings
3) Click on Font tab and on open font file. 
4) the select file dialog opens. Note there is no *.tff

### ImHex Version

1.31.0

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Portable

### Additional context?

The error doesn't occur in last release so a recent change must have created this. The source code lists both .tff and .otf, but when the vector of filters is emplaced the tff becomes otf for some unknown reason.

**Comment by WerWolv** [comment]
The issue was that the content of the `validExtensions` vector was copied instead of used by reference. So the strings were copied, a pointer to the data was stored in the `validExtensionsNfd` vector and then the strings were destroyed again, leaving a dangling pointer behind. "Lucky us" that didn't crash, it just produced invalid behaviour

**Comment by paxcut** [comment]
I did try to fix it for a while because it seemed like an easy thing to fix but gave up to pursue other pressing issues instead. Still I was curious about what was happening. The explanation on the last post makes it clear what was wrong and I thank you for that.
