### ISSUE TITLE
[Bug] "Copy as > Go Array" generates syntactically invalid code 

### ISSUE THREAD

**Issue by cedws** [WerWolv/ImHex#1391]
### Operating System

Windows

### What's the issue you encountered?

When using `Copy As > Go Array` to copy bytes as a static Go byte array, the generated array is syntactically invalid because of a missing trailing comma, which is required.

This is caused by `formatArrayLanguage` removing the final trailing comma.

https://github.com/WerWolv/ImHex/blob/bffc229fa8971f0b13d8fa79e57127683c42111d/plugins/builtin/source/content/data_formatters.cpp#L35-L38

### How can the issue be reproduced?

1. Create new file
2. Select first byte and click `Copy as > Go Array`
3. Observe that the following code is generated:
```go
data := [...]byte {
	0x00
       // required: 0x00,
}
```

### ImHex Version

v1.29.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Scoop

**Comment by paxcut** [comment]
C++ enumerations also allow the last element to be followed by a comma, but this is optional, not required, and not including it does not make the code syntactically incorrect. I know little about Golang syntax, but I can find lots of examples of Golang byte array code in the internet that do not include a comma after the last byte of the array. 

More generally, I cannot find any evidence that supports the claim of syntactic incorrectness of generated code. What are the bases of such claim? If the claim proves to be correct then my opinion of the language will suffer as it would for any language that requires trailing commas after last element of a list or array because in my opinion that would be  an arbitrary and unnecessary requirement that makes the code look  worse.

**Comment by cedws** [comment]
Here is a playground link that shows it will not compile.

https://go.dev/play/p/ZKG6hLEWwO8

**Comment by paxcut** [comment]
the error was that the } cannot be in the next line . the following code gives no error
```cpp
func main() {
	_ = [...]byte{0x00}
}
```

**Comment by cedws** [comment]
Yes, it is required if there is a newline inserted, as ImHex does.

As an aside, it would be good to also remove the space in `[...]byte {` as the Go formatter will remove it anyway.

https://github.com/WerWolv/ImHex/blob/bffc229fa8971f0b13d8fa79e57127683c42111d/plugins/builtin/source/content/data_formatters.cpp#L82C84-L82C84

**Comment by WerWolv** [comment]
Huh weird syntactical choices, I didn't expect that. I'll fix it 👍

**Comment by paxcut** [comment]
That doesn't make it a requirement because the newline doesn't need to be added. Adding the newline is the mistake and adding a comma to fix it would be a second mistake. That comma simply implies that more elements may follow in other lines but since there are no more elements then the closing brace should follow the last element immediately after.
