### ISSUE TITLE
[Bug] [Web] ImHex detects if first visit before any license agreement/cookie agreement

### ISSUE THREAD

**Issue by tilkinsc** [WerWolv/ImHex#1472]
### Operating System

Windows

### What's the issue you encountered?

I think you might want to accept cookies and the like before performing such messages. Perhaps a license agreement as well. This infringes europe laws.

From: https://web.imhex.werwolv.net/

### How can the issue be reproduced?

Visit https://web.imhex.werwolv.net/ for the first time

### ImHex Version

Latest

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Web

**Comment by WerWolv** [comment]
Hi, thanks for the report.

There's no cookie popup because we don't use any cookies to store information on the site as can be seen through e.g Firefox's dev console: 
![image](https://github.com/WerWolv/ImHex/assets/10835354/7126be75-ad27-49b6-bcea-9d0af3920bd2)

There's also no license agreement since ImHex is under a Open Source license only which can be _acknowledged_ but not agreed to. 

If there's anything that's actually against the law, please let me know and I'll try to improve it.
