### ISSUE TITLE
[Bug] Numpad Navigation Keys don't move the cursor.

### ISSUE THREAD

**Issue by shimamura-sakura** [WerWolv/ImHex#1475]
### Operating System

Linux

### What's the issue you encountered?

Navigation keys of numpad (home, end, arrow keys etc.) don't move the cursor.

### How can the issue be reproduced?

Try to move the cursor with numpad keys in hex editor or pattern editor.

### ImHex Version

1.32.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

archlinux package

**Comment by WerWolv** [comment]
Thanks for the report. This wasn't really a bug, just something that we never implemented. The numkey buttons are distinctly different from the regular home/end/pgdn/pgup or the arrow buttons so that conversion just doesn't happen automatically.
The latest commit now implements this functionality when Num Lock is disabled.
