### ISSUE TITLE
[Bug] including std/core and std/mem at in the same file crashes imhex

### ISSUE THREAD

**Issue by Calcoph** [WerWolv/ImHex#1641]
### Operating System

Windows

### What's the issue you encountered?

If I try to include both `std/core.pat` and `std/mem.pat` imhex crashes.

### How can the issue be reproduced?

1. type in the pattern editor:

```C
#include <std/core.pat>
#include <std/mem.pat>
```

2. Press "run".

### ImHex Version

1.33.0 a7033b6

### ImHex Build Type

- [x] Nightly or built from sources

### Installation type

MSI

**Comment by glpnk** [comment]
Use `import` statements now

```rust
import std.core;
import std.mem;
```

Also, this happens on Linux too

**Comment by paxcut** [comment]
I have known about problems including those two files for a while which is caused by all files using import internally, but it didn't crash imhex before.

**Comment by C3pa** [comment]
Ok, on Windows 10, ImHex v1.35.4 `#include`ing both headers won't crash ImHex but triggers a stream of errors.

**Comment by paxcut** [comment]
thats normal because include and import use different pragma once systems so they can't be mixed. Because all headers use import internally when you include core it imports mem so when you include mem you get duplicate errors.

**Comment by C3pa** [comment]
Ok, so is it now recommended to only ever use `import` with built-in libraries?

**Comment by paxcut** [comment]
All the headers that are installed with ImHex use import internally so it makes sense to use import in order to use them to avoid problems like the one presented here. 

If you make your own headers to use in your patterns then it depends on what features you want to use. if you want to use preprocessor features like `#define` or `#ifdef` then you need to use include because import doesn't propagate macro definitions. import uses the as syntax to create namespace aliases but `#define` can do the same and even more. Both systems have their pros and cons and it is a pity that they can't be used at the same time, but the way they are both designed makes interaction impossible.
