### ISSUE TITLE
[Bug] 3d visualizer becomes extremely slow without axis disabled

### ISSUE THREAD

**Issue by mandar1jn** [WerWolv/ImHex#1663]
### Operating System

Windows

### What's the issue you encountered?

Whenever the axis are disabled for the 3d visualizer, every rotation takes a few seconds to apply and only applies after having let go of the middle mouse button.

### How can the issue be reproduced?

open a 3d model file and run its pattern
open the 3d visualiser
disable the axis (every other option doesn't matter)
try to rotate the model. Wait a bit between interactions
enable axis again
successfully rotate the object accurately again

### ImHex Version

1.33.2 (latest nightly

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

MSI

### Additional context?

unable the model due to copyright concerns. Please contact me on discord if needed (same username)

**Comment by paxcut** [comment]
To be able to reproduce this issue several conditions must be met that are not described in the description above. The conditions also affect how the issue manifests itself. The conditions are:
1) There is no text (2d) being displayed in the 3d view. For most that means turning the axes display off. For some, if running a debug build, it is impossible because the mouse coordinate display cannot be turned off.
2) The entire 3d visualizer window must fully overlap the main ImHex display.  To clarify, the issue won't be reproduced if the 3d visualizer window intersects the main ImHex window outer border or if it lies completely outside.
Under those conditions you will experience lag on the rotations and translations and scaling of the model. Just how much lag depends on  whether you have the option Extra>Settings>Interface tab=>"Show resources in footer" on or off. If it is on then the model will update when the % cpu updates to show a new value. If it is off the model updates when you hover over the icons or the reset button. If you are rotating the model with the middle click, the model will not update by simply lifting the middle button, you have to hover the items described for that to happen.

**Comment by paxcut** [comment]
The reason for the bug, as will be shown soon, is that the lag occurs when there are no draw calls changing between frames despite the fact that the 3d contents is changing. The reason the 3-d changes become invisible to the optimization code should be obvious. There are no draw calls being made from the opengl code that renders the visualization. It is true that a texture is created, but it isn't being displayed using draw calls. To see this we turn to the Imgui demo and the `ShowMetricsWindow` function which allows the highlight of draw calls in real time. The reason why this wasn't done before is that the Imgui demo requires you to click open the node you want to show the draw calls of and hover it. First you can't open the node because as soon as you click on the tool's window the 3-d visualizer window closes. Even if you could open it, the focus will remain on the 3d window so hovering other windows wont register.

I found the code in the demo that renders the draw call highlights and made changes to it so that the draw calls of the 3-dvisulaizer window are always drawn. When the name of the window contains Popup it calls `ImGui::SetNextItemOpen(true);` which ensures the node will be open on creation while defining a boolean that can be used to remove the need to hover. This is what happens:

https://github.com/user-attachments/assets/50e428c0-7353-4fb4-b989-75050989310e

As you can see, the 3d display does not produce draw calls, so the optimization thinks there are no changes in the display and skips the rendering until some other part of the window updates as explained in my previous post, thus creating the lag. 

There are two possible approaches that I can think will solve the problem. The easiest to imagine and implement is to add a permanent draw call to 3d windows that updates every frame. The other would be to communicate to the function doing the optimization that there's a 3-d image and have the optimization turned off. I know how to implement the first but not the second and looking into it doesn't seem worth it when an equally good solution that's easier to implement is available.
