### ISSUE TITLE
[Bug] #endif is considered an invalid directive if anything is on the immediate line after

### ISSUE THREAD

**Issue by EtiTheSpirit** [WerWolv/ImHex#1715]
### Operating System

Windows

### What's the issue you encountered?

Bit of a strange one here.

If more than one static branch is used in a file, they must be broken apart by at least one line, lest `#endif` be unrecognized as a directive.

### How can the issue be reproduced?

Create a new file (can be blank), and open the pattern editor.
Enter the following code to the pattern:
```
#ifdef GARBAGE
#endif
#ifndef GARBAGE
#endif
```
Attempt to compile this code. Line 4 will raise the following error:
```
E: error: Unknown directive 'endif'
E:   -->   in <Source Code>:4:7
E: 4 | #endif
E:           ^
```

Add a line break separating lines [1,2] and [3,4] as such:
```
#ifdef GARBAGE
#endif

#ifndef GARBAGE
#endif
```
Attempt to compile this code. This will succeed.

### ImHex Version

1.33.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI, Non-portable

**Comment by paxcut** [comment]
This bug was fixed already on master (1.333.0) and the code without any spaces should compile and run without errors on a recent nightly master build. I just tried it on a May 14 nightly without any problems.

![image](https://github.com/WerWolv/ImHex/assets/53811119/ee68baab-dbcd-4d15-843f-d20a6fb2f77a)
