### ISSUE TITLE
[Bug] Pattern highlighting not propagating to parent for fields with pointer locations

### ISSUE THREAD

**Issue by rumblerosesxx** [WerWolv/ImHex#1803]
### Operating System

Windows

### What's the issue you encountered?

It seems that clicking on fields that are dynamically allocated does not properly propagate the highlighting to its parent in Pattern Data section. This makes it difficult to identify which item in the list the given file location is associated with.

### How can the issue be reproduced?

Using something like this:

 ```
struct Mesh {
  u32 bones[20];
  u32 size;
  u32 vertex_table_addr;
  u32 vertices[size] @ vertex_table_addr;
}

Mesh meshes[20];
```
Now click on a member of the bones field and it will highlight the parents all the way to the top level as expected. However clicking on a member of the vertices field does not propagate the highlighting to the top level and stops at highlighting vertices field but not its parent Mesh list member.

### ImHex Version

1.35.3@dffb7e9

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by paxcut** [comment]
The reason the highlighting is not propagated is not because the array uses a variable to set its size but rather from the use of the place operator (@)  You can test that by creating a pattern that allocates data dynamically but doesn't use calculated pointers. You will see that ImHex has no trouble highlighting the parents.
For a simple example of this try the following code. For input use data `0x01 0x02 0x03 0x04 0x05`
```cpp
struct Test {
    u8 magic;
    u8 size;
    u8 address;
    u8 data[size] @ address;
};

Test t@0;
```
Using the code above you will see that just like your code highlighting data doesn't propagate up. Now change the code so it looks like this
```cpp
struct Test {
    u8 magic;
    u8 size;
    u8 address;
    u8 data[size];
};

Test t@0;
```
The size is still allocated dynamically, but now highlighting works its way up. To verify the issue is with the place operator use the code
```cpp
struct Test {
    u8 magic;
    u8 size;
    u8 address;
    u8 data @ address;
};

Test t@0;
```
Now data is not allocated dynamically, but highlighting doesn't propagate from it either.

I don't know if the highlight behavior for calculated pointers is intended or a bug, but the title should reflect that the issue is with the @ operator and not with dynamic allocation.

**Comment by rumblerosesxx** [comment]
@paxcut looks like you're right, I didn't suspect the @ but looks like that's the real issue. I updated the title. Thanks!

**Comment by WerWolv** [comment]
Hey
This is simply because placements within struct-like objects don't contribute to the size of their parent. For example if you write
```cpp
struct Test {
    u32 x @ 0x00;
};
Test test @ 0x00;
```
then `sizeof(test)` is equal to zero. The highlighting then later on makes sure that the address of the hovered byte is within the range of the parent object as a performance optimization. It's simply not viable to search through all the children to find the right one because patterns can potentially have millions of children (for example arrays). Since in your case, vertices array is not within the extents of the parent struct anymore, it doesn't get highlighted.

This is therefor intended behavior and not a bug.

**Comment by rumblerosesxx** [comment]
Thanks for the explanation! I don't have a good sense of how much effort it would be but would it be possible to have a right-click menu option, or similar, to search for all parents of the given location? That way normal search optimizations could be ignored and the user could trigger an expensive operation to identify all parents. Cheers!

**Comment by WerWolv** [comment]
There's only ever going to be one pattern. What we have is the `Right click -> Jump to -> Pattern` option that jumps to the currently selected highlight's pattern entry in the pattern data view. There you'll see the parent and all of its siblings next to each other

**Comment by paxcut** [comment]
You can also have many parents,
```cpp
struct Test {
    u8 magic;
    u8 size;
    u8 address;
    $=address;
    u8 data[size];
};

Test t@0;

struct Test2 {
    u8 val1;
    u8 val2;
    u8 data[t.size];
};
Test2 t2@3;
```
![image](https://github.com/WerWolv/ImHex/assets/53811119/b11a5456-4275-43a7-87c0-ea6de608ab51)

**Comment by rumblerosesxx** [comment]
Cool thanks guys, between Jump to->Current Parent and using cursor manipulation to lay out the child structs I think I should be all good. Cheers!
