### ISSUE TITLE
[Bug] placement doesn't work in if outside of a struct

### ISSUE THREAD

**Issue by Jimmy-Z** [WerWolv/ImHex#1829]
### Operating System

Windows

### What's the issue you encountered?

as title

### How can the issue be reproduced?

create a new file, use this pattern
```
if (true)
    u8 test @ 0;
```

### ImHex Version

1.35.4

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

portable

**Comment by WerWolv** [comment]
Hey, this is intended behavior. The global scope, for the most part, behaves like the inside of a function so placements inside of ifs turn into views.
If you need logic like this, put it in a struct and place down that struct then.

**Comment by Jimmy-Z** [comment]
`if` in global works, placement in global obviously also works, so why wouldn't placement inside if work?

And what is "view"?

**Comment by WerWolv** [comment]
It's just a side effect of how the global scope works. 
Basically the global scope acts as if the code is run inside of a `fn main() {}` with the exception that it allows placements.

When you try to place down patterns inside of a function, it can't just add them to the output because that would potentially produce multiple patterns with the same name in the same scope. Instead what it does is create a "View". It acts as if it places down the pattern so you can access the members of that pattern but it doesn't add it to the output. When writing an if() in the global scope, it interprets that as if it was an if() inside of a function instead of as an if() inside of a struct.

This behaviour is documented here, but I guess it could benefit from a more explicit mentioning of it
https://docs.werwolv.net/pattern-language/core-language/functions#global-scope
https://docs.werwolv.net/pattern-language/core-language/functions#pattern-views
