### ISSUE TITLE
Don't render when not necessary

### ISSUE THREAD

**Issue by Flamaros** [WerWolv/ImHex#189]
The application should avoid to draw when not needed to reduce power consumption.

I think that it is critical to be able to work correctly on a laptop.

PS: I reported some other issues, it's because I find ImHex pretty cool and useful. Thank you.

**Comment by TrueBers** [comment]
Or should at least have an optional FPS limiter, like 30 or 15.
60 FPS for a hex editor is pretty much overkill.

<img width="189" alt="imhex" src="https://user-images.githubusercontent.com/1314261/110204112-5ad9bf00-7e82-11eb-94a9-19650dc78b6f.png">

15% of i7-7700HQ CPU and 28-30% of GTX1050 GPU load is *enormous* for an idling editor. My laptop is gonna hate me soon.
The editor is really nice, but we definitely have to do something with that global warming load percentage. It's unusable on a laptop without connected power supply.

**Comment by WerWolv** [comment]
Added a few fixes for this issue with the latest commit.
First of all, ImHex will no longer render at all when the window is not visible or if it's been minimized. Second, I added a setting now where you can choose an FPS limit between 15FPS and 60FPS. Everything below 30 does become kinda laggy but I figured some people might still want it. 
If there's anything else that should be done, please let me know.

**Comment by Flamaros** [comment]
Sorry for late answer.
I think that it is already a really good improvement, but for really saving the battery I think that the application shouldn't render if there is not change at all, even when having the focus.

When developing mobile applications the gain was really huge between slowing down the refresh rate and only rendering when the graphical scene changed. Generally there is only a flag to put at true when an processed input trigger something that require a redraw like a button hover event,...
Things become more difficult when the application can display animations because in this case when animations ends, the rendering mode have to come back the on-demand one.

I don't know if Dear ImGUI provide a flag to notify if the scene changed (Qt-QML do this with his scenegraph).

In all cases, I'll take a try with the next release. I really appreciate the latest improvements. Thx

**Comment by mirh** [comment]
Indeed, it seems completely stupid for an UI to render on the same principles of a 3D game.
https://github.com/ocornut/imgui/issues/2268

**Comment by WerWolv** [comment]
This has been fixed a while ago though

**Comment by mirh** [comment]
Not really? Both my cpu and gpu have a quite significant load when the program is open.

**Comment by Tey** [comment]
@WerWolv [The way you use `ImGui::IsWindowFocused()`](https://github.com/WerWolv/ImHex/blob/7f0bdc95dad9f3774f11cae0a4a7a8f784eb1d90/source/window.cpp#L410) to detect if the application has the focus does not work (at least on Windows). From my understanding of ImGui code, the `ImGuiFocusedFlags_AnyWindow` flag will only tell you which of the GUI or the underlying game has the focus, it does not tell you if the program has the focus. Thus, since there is no underlying "game" for ImHex, `ImGui::IsWindowFocused(ImGuiFocusedFlags_AnyWindow)` always returns `true` on Windows, even when another application has the focus.
You should probably use the [focus callbacks](https://www.glfw.org/docs/latest/window.html#window_focus) from glfw to detect that instead, but I haven't tested.

IMHO, ImHex still uses too much CPU than it should for rendering. To reduce that even more, you could prevent rendering a new frame in the lack of input events, as you do when the app is minimized. The only drawback is that it also prevents event-less animations to play. One middle ground is to use a small FPS in the absence of events, and keep using a high FPS for events so that the app is still responsive. Something like that:
````diff
diff --git a/source/window.cpp b/source/window.cpp
index ef41139..c839abc 100644
--- a/source/window.cpp
+++ b/source/window.cpp
@@ -186,9 +186,11 @@ namespace hex {
         this->m_lastFrameTime = glfwGetTime();
         while (!glfwWindowShouldClose(this->m_window)) {
             if (!glfwGetWindowAttrib(this->m_window, GLFW_VISIBLE) || glfwGetWindowAttrib(this->m_window, GLFW_ICONIFIED))
+                // Only render when new events are received
                 glfwWaitEvents();
-
-            glfwPollEvents();
+            else
+                // Render at 5 FPS when no new events are received
+                glfwWaitEventsTimeout(this->m_lastFrameTime - glfwGetTime() + 1 / 5.0);
 
             this->frameBegin();
             this->frame();
````

I haven't seen any animations in ImHex that requires more than 1 FPS to run, so maybe this should be the minimum FPS goal instead of 5. Or even better, let the users select the value they want through a parameter (making it possible to be less than 1 FPS maybe).

With latest source code from the master branch, ImHex uses around 6% of my CPU when idle. When using a minimum of 5 FPS, it uses around 1% of CPU, and this goes down to 0.1% with 1 FPS, so that might be significant for battery powered devices.

On a side note, `glfwWaitEvents()` and `glfwWaitEventsTimeout()` do call `glfwPollEvents()` when an event is available.
