### ISSUE TITLE
[Feature] Pasting text in hex editor

### ISSUE THREAD

**Issue by EGNL** [WerWolv/ImHex#1904]
### What feature would you like to see?

I would like to see being able to paste text in files with ImHex's hex editor. Currently, it is only possible to paste bytes into files.

### How will this feature be useful to you and others?

For certain people, this feature removes the extra step of converting your text to bytes.

### Request Type

- [ ] I can provide a PoC for this feature or am willing to work on it myself and submit a PR

**Comment by BioTheWolff** [comment]
I have looked into it and found a few ways to implement it.

One way would be to implement a different kind of paste (bytes or text) depending on the type of region you are focusing on (bytes, or their representation in the right column). However, I found two flaws to that:
- Currently, the selected region event does not provide information of whether you are selecting bytes or their representation (also, both selections are directly tied to one another);
- This would have to be described through documentation, because there is little to no room in the UI to properly explain the difference in pasting behaviour.

Another way would be to calculate (which is to say, literally guess) whether the clipboard contains plaintext or an ImHex-formatted array of bytes.
This seems to me like a bad idea, because there are many ways to interpret a given string, and the function could fail in delivering the expected result, without any way for the user to override this behaviour.

Finally, we could create a new, specialized keybind in the likes of "Paste all as text" (that could be tied to `Ctrl + Alt + Shift + V`).
It would allow users to voluntarily paste as plaintext, which would cause ImHex to transform text to its bytes array equivalent before writing to the region.
This also solves many edge cases, i.e. copying bytes and pasting them as text that could work flawlessly as it's an explicit user-requested action.

@WerWolv What are your thoughts on this?

**Comment by paxcut** [comment]
Why not use the mouse location to decide where you are pasting to. If the mouse is over the column then paste as ASCII. If the mouse is over the hex values then paste as binary. This would be similar to how Imhex is able to edit the data as ASCII (by selecting an offset on the ASCII column) or as binary (by selecting an offset of the hex editor proper).

**Comment by iTrooz** [comment]
Assignee: @BioTheWolff
