### ISSUE TITLE
[Feature] floating or draggable window of view

### ISSUE THREAD

**Issue by Chauhan-Aniket** [WerWolv/ImHex#1922]
### What feature would you like to see?

1. **put paste button to direct paste**
2. **make if floating or draggable window, or change that place**
3. **real time search & instead of selection for HEX or String ,view both results side by side** 
4. **runtime number finding with hex or decimal feature with little or big endian** 
5. on next search don't clear search box 

**- Search box hiding hex value**

![image](https://github.com/user-attachments/assets/f9d8d76a-85a4-46a4-9dc5-83c30d835354)

**- Selection on next search**

![image](https://github.com/user-attachments/assets/889514ee-ecfe-4bb8-822e-ae0c6993d71c)

### How will this feature be useful to you and others?

1 : direct paste of clip board
2 : left corner of hex view is not visible when search found in that area
3 : some time its crucial to compare & match or get ascii value , when reversing such chunk its helpful to just pass desired result which may be stored in other format
4 : finding big or little endian number with Hex or decimal 
5 : pressing search & again fill text box is little bit annoying   , so don't clear or just make selection of that word that user will clear or pressing right arrow & continue next search

**Comment by paxcut** [comment]
This is meant to be a simple search. Some of the features asked for don't belong here and should be requested of the advanced search instead.

- I don't understand how paste is related to search. Do you perhaps mean to request that a find/replace feature like the pattern editor has be implemented for the hex editor as well?
- Maybe you are on an old version, but the search window is both drag-able and it also becomes transparent when mouse is not hovering over it, so you should be able to see what search has found without any problems.
- I am having trouble parsing this part. It is not possible to search for numbers and ascii at the same time unless both represent the same data. It may be possible to do away with the binary vs string by allowing the specification to be part of the search format. That is an advanced feature and this is meant to be a simple search.
- decimal search is an advanced feature that is currently not supported. Using endianess for number searching is more confusing than not using it. does the search mean that the input is in little endian or does it mean to find the little endian of the input? Strings are always written in big endian so there is no ambiguity there. If you want to find bytes in the order opposite than they are found then write them in that order in the search window.
- Again you may be using an older version because currently, when you press Ctrl-F or select file>find on the menu, the search window opens with the content it had when you last used it. That is cleared only when you switch to/from ascii. to search repeatedly use the up/down arrows.
