### ISSUE TITLE
[Bug] Can't use pointers in functions/if/loops

### ISSUE THREAD

**Issue by RomanJos** [WerWolv/ImHex#2018]
### Operating System

Windows

### What's the issue you encountered?

Hello, do pointers are forbidden in functions ?
By the way this is mostly an issue for pattern code but I believe opening an issue on the main program could help more
```
u32 that_work @ 0;
u32 *that_work_too :u32 @ 0;

if (1) {
 u32 that_work_also @0;
 u32 *error @ 0;
};

fn test (){
 u32 that_work @ 0;
 u32 *error @ 0;
};

while(1){
 u32 _that_work @ 0;
 u32 *_error @ 0;
};
```

```
E: error: Expected identifier in variable declaration, got Operator (*).
E:   -->   in <Source Code>:16:1
E: 16 | u32 *_error @ 0;
E:      ^^^
E: error: Expected ';' at end of statement, got Operator (*).
E:   -->   in <Source Code>:16:1
E: 16 | u32 *_error @ 0;
E:      ^^^
I: Evaluation took 0.0003435s
```

### How can the issue be reproduced?

a

### ImHex Version

1.36.0 commit 6ab2e81
I also tested on ab12503 which removes newlines in the console?
![image](https://github.com/user-attachments/assets/84824e44-3ac3-41e7-bfec-7abb06cf7ba3)

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

MSI

**Comment by paxcut** [comment]
You are mixing pointer definition with the placement operator which makes the idea of a pointer more complicated that it needs to be. A pointer is only beneficial when used inside a struct. consider the following code
```cpp
struct S {
   u8 value;
   u8 address;
   u8 v @ address;
};
struct S2 {
   u8 value;
  u8 *pointer : u8;
};
S s1 @0;
S2 s2 @0;
```
they both do the same thing, but the second one will create also an entry for the pointee in the pattern data window.
Using pointers in functions makes no sense. The code
```cpp
fn test() {
  u8 *p : u8;
};
```
Doesn't have any meaning because function variables cannot be placed without a placement operator. You can argue that it should be allowed when using a placement operator but still that will get you nothing that a simple variable holding the address gives you already because variables placed in functions don't show in the pattern data window so you don't get the extra advantage shown above. Instead of writing
```cpp
fn test (){
 u32 that_work @ 0;
 u32 *error : u32 @ 0;
};
```
you would write
```cpp
fn test (){
 u32 that_work @ 0;
 u32 this_works  @ that_work; 
};
```
to get the desired result

**Comment by RomanJos** [comment]
Well I get what you guys are saying but unless I'm tripping using pointers avoid using two variables and it helps emulate behavior from pseudo-code before getting a grasp of the layout, and placing definitely place a variable in the editor in its inside a function ? 
![image](https://github.com/user-attachments/assets/4ffe56ef-296d-430a-866d-969b05d8fe6d)

**Comment by paxcut** [comment]
You can only use one variable in a placed struct. I showed that in my example where i emulate a pointer using the placement operator which requires an extra variable that will have zero size. Variables in functions cannot be placed without the placement operator so you always need two variables to place inside a function. The pointer syntax would do nothing that you can't already do without it because only inside the struct you can use one variable to be used both as the address and the pointer the address is pointing to.

**Comment by RomanJos** [comment]
Okay so :
```
struct S {
   u8 value;
   u8 address;
   u8 v @ address;
};
struct S2 {
   u8 value;
  u8 *pointer : u8;
};
struct S3 {
   u8 value;
   u8 address;
   u8 offset;
   u8 *v : u32 @ address + offset;
};
```
Structures support all of this while functions support only the former, now is it a design choice or because of how functions require a size or a view or whatever ? If you could list all the scopes at works in the parser, what they expects and whats their purposes I think it could clear things up, I mean having a talk about the internal of the DSL processor because right now I can tell you that I am confused; structures support more data manipulation than functions. Now, if it is a design choice I would recommand to name them macro or something else and write a spec of this DSL mentionning drawbacks coming with a declarative approach, how it is perhaps not a great choice if your goal is to emulate a program while visualising data using this editor.

A declarative approach feels like working against the current when reversing a program because of its nature, that is the root of my problem and why I went to a functional way of parsing the file at first, I believe I am not alone facing this problem; my current approach is looking at functions taking integer etc from the files and logging their executions with the requested offset, along with their "parent" function with arguments etc, my starting point is the last variable I will write in imHex, your software helps in writing definition of a file's structure but not discovering it, I could use better software for that man

However what is the data processor for ? I see a bunch of nodes gets connected ones towards anothers in a step-like manner, much like how a program evolve, my two cents but setting colors automatically on links depending on their deepness in the execution, instead of the random thing you have in place, could bring forth a pseudo-structure of the file as the program sees it, one could start building functions reading from memory towards abstract one in that "data processor" workspace in the same order it decompile them, even building a list of calls to one function along with arguments to each of them and feeding that against its implementation would help "validate" that and move on, step by steps a pseudo-structure would build itself and that would be much better to resonate over it in my opinion.

If you guys could write a spec or clear rules about how the pattern "compiler" work that would help a lot I guess we can close this issue

**Comment by paxcut** [comment]
creating a pointer in a function makes no sense. Look at the following code.
```cpp
struct S2 {
  u8 *pointer : u8;
};
S2 s@0
fn S() {
  u8 *pointer : u8;
};
```
The function has no functionality to determine what the address of the pointer will be. The structure gets the address when it is placed from the input file, but you can't do that with a function. 

Lets look at this one concept at a time.  There are two main concepts being thrown together. They are pointers and variable placement. Both concepts are related and on top of that they can also be combined which makes them powerful constructs but can also be confusing when mixed together. 

The simplest of the two is that of variable placement. You have a variable type, a variable name and an address and you want to read the data at the address as if it was a variable of the given type and assign it the given name. The size of the data read is the size of the variable type so you write `Type name @ address;`

A pointer is a related concept but a bit more complex. You also have an address, a variable type and a variable name. The intention is different than that of a variable placement. You want to read data from the input file, treat that data as an address and create a variable of the given type at the address using the given name. The part that is missing is the type (size) of the pointer which determines how much data you want to read. so you write `Type *name : pointerType;`

The pointer is really a shorthand for two operations, one is to read a variable as an address and the other is to use the address together with a type and a variable name to define what was stated in the description of a variable placement. To be of full use, pointers are not placed inside structs, they obtain the address from the input data and that is something functions cannot do. That fact alone makes pointer syntax illegal in functions.

Since any variable can be placed and pointers are also variables it follows that you can place pointers as well. That is a consequence of the syntax, and the interpretation is what you would expect, but you need to compensate for the fact that the pointers don't actually read any data from the input file.  The address is no longer being read from the file as a normal pointer would but it is supplied in the placement operator so it is not reading data. 

As for functions, they don't allow the pointer syntax inside of their bodies because you can't define a pointer in general. Lets assume that we somehow make the syntax available for functions. You still need to supply an address for them so they would need a placement operator to be defined. so you would write `Type *name : pointerType @ address;`
This is no longer a shorthand because it needs the address. If the address is fixed then you are better off defining that variable in the global scope where it becomes available to all structs and functions by name. If the address is from some variable then you need two statements to define the pointer so instead you write `pointerType pointerAddress @ adress; Type name @ pointerAddress;`. That gets you the exact same thing with the same number of statements and without the need to use pointer syntax so the need to allow it is not created.
Yes structs are at the center of the pattern language (we call them patterns) and have more capabilities than anything else. They are designed that way. Functions and function like statements cannot create patterns that are seen in the pattern data window or highlighted in the hex editor. they are simply reusable code to help structs do their job which is to create patterns that help  you describe the contents of binary files. Not to determine the structure, for that there are numerous tools in ImHex that get information from the input file for you to analyze and determine the structure. The pattern language is descriptive, you need to know what data is located where to write a pattern that shows you the values for any input file of the right type.

**Comment by RomanJos** [comment]
I'm so sorry I didn't removed the second class in my example, of course I have to supply an address using @, I wanted to emphasize on my third example, that would need two variables instead of one pointers
Again, excuse me for leading you in the wrong direction, please continue about
>As for functions, they don't allow the pointer syntax inside of their bodies because you can't define a pointer in general.

Not having the value displayed in the editor is not a problem, I wanted to use addressof(pointer) and pointers in functions, that is all and the workaround you proposed using two variables is an option but defeat the purpose of supporting pointer in the first place, a pointer is like an automatic two value if you wish, addressof gets the first and variableName the second
Also, we are talking about functions while I want to conditionally build a pointer based on specific logic or do nothing, technically I never used any function, just if statement that are creating their function (it seems?) So that too has to be taken into account in my motive to create pointers that way, I'm really sorry to have led you in explaining the obvious I hope we can resolve it now !

**Comment by paxcut** [comment]
How are you able to define a pointer using only one variable? the only way I can think of is to use a literal for the address. 

If you are using literals for the addresses, then those pointers belong in the global scope, not inside a function. When placed in the global scope they become global variables that can be accessed inside functions and inside structs.

 If you re not using literals as addresses then you would need a variable to hold the value of the address. That means that the pointer syntax no longer provides the one variable advantage.  To define pointer like behavior inside functions you use the placement operator which can always be used for that purpose in any scope.

**Comment by RomanJos** [comment]
Can I just have someone more competent here for god sake

**Comment by WerWolv** [comment]
Yeah I think you're trying to use the pattern language in ways that it was not really intended. If you want a more functional approach, by all means use Python. You'll have a much better time.
The pattern language is about defining structures (as fine grained as you need them to be) and putting them together to decode the entire file. This works great for basically all file formats out there but it requires some rethinking if you're used to regular programming languages.
The pattern language can still have regular functions and logic like you're used to in other programming languages and you can use them to parse things. The only thing you cannot do is put things in the pattern output (the table in the pattern data view) from within functions.

The data processor on the other hand is a completely different thing. Do you know CyberChef by chance? It's the same idea basically. You read in data, transform it in various ways that makes sense for your data (decryption, byte-wise arithmetic, etc) and overlay that data back over the original bytes. It allows you to work with encoded file transparently without having to use an external tool to decode it first.

Lastly, I'd like to ask you to stay civil. That comment was very uncalled for.

**Comment by WerWolv** [comment]
There's really two confusions here. The first one is about views and the second one is about pointer views.
Ifs not behaving the same in the global scope as in types is intended behaviour and correct.
Pointers not being placeable as views in function contexts is an oversight and should be fixed on our side.

**Comment by RomanJos** [comment]
👌 perfect
And sorry for losing my nerve I appreciate the work you're doing
