### ISSUE TITLE
Convert sizes to human-readable units is always on

### ISSUE THREAD

**Issue by LennardF1989** [WerWolv/ImHex#2024]
### Operating System

Windows

### What's the issue you encountered?

The language key to toggle is still there: 
```
"hex.ui.hex_editor.human_readable_units_footer": "Convert sizes to human-readable units",
```

Is it intentionally always on?

I think the whole area is being reworked where this button was originally was. 

That said, I liked where the selection text was originally. It's now in the status bar, which makes it impossible to select and copy the values.

### How can the issue be reproduced?

Start ImHex :D

### ImHex Version

1.36.0

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

MSI

**Comment by WerWolv** [comment]
Hey, you're not the first one that voiced concerns about me moving the selection to the status bar. This change was mainly done because the hex editor footer was extremely cluttered and looked terrible but also because many many other applications have that information in the same place.

CLion:
![image](https://github.com/user-attachments/assets/a0aa9683-ee07-4910-bb05-954aa13b406b)

VSCode:
![image](https://github.com/user-attachments/assets/65b05da6-54e1-4eaf-aad6-4679c0bef72a)

HxD:
![image](https://github.com/user-attachments/assets/b5481c23-09a9-438b-a5b7-bd5e47cb8369)

Notepad:
![image](https://github.com/user-attachments/assets/9cf8e700-b639-4cc2-a933-bacac195bf6e)

None of these are actually selectable. Would it improve things if I made it clickable? 
The "Convert sizes to human-readable units" option disappeared because even before it only affected the size of the selection which is now always displayed in both hex and as human readable bytes so there wasn't any need for it anymore.

**Comment by LennardF1989** [comment]
I like the original position over the statusbar. Whenever I reversing file formats, I'm constantly checking selections and offsets and it being in the statusbar feels like a "long distance" from where the action is happening.

This is my usual layout:
![image](https://github.com/user-attachments/assets/2e44f53a-b861-46e7-bc0e-abc9999ffb26)

Being able to "click to copy" could work, but I would like all things to be a separate entity in that case, like HxD is doing it.

**Comment by WerWolv** [comment]
Latest commit adds a setting that moves the selection back to the hex editor footer if desired. 

![image](https://github.com/user-attachments/assets/b29d1db5-0360-46b6-894c-abbfa028eb82)
![image](https://github.com/user-attachments/assets/b9ac5e61-2d24-41e4-93a4-ee5e6fc6776e)
