### ISSUE TITLE
Windows detected malware in "Portable ZIP" file

### ISSUE THREAD

**Issue by Husamdababneh** [WerWolv/ImHex#214]
![image](https://user-images.githubusercontent.com/19290128/113288886-2c6fc800-92f8-11eb-85cb-1d7914c694e5.png)

**Comment by WerWolv** [comment]
Uh well as you can see, the entire source code of ImHex is available for you to go through to check for yourself and compile it on your own if you don't trust the release. I don't know what the Windows Defender thinks is bad about ImHex but it's nothing I can really change

**Comment by Husamdababneh** [comment]
> Uh well as you can see, the entire source code of ImHex is available for you to go through to check for yourself and compile it on your own if you don't trust the release. I don't know what the Windows Defender thinks is bad about ImHex but it's nothing I can really change

Don't get me wrong.. of course I can view and compile the code.

Just wanted issued the issue to see if it's resolvable .

Thanks you and have a nice day

**Comment by WerWolv** [comment]
I'm sorry if I sounded rude. 
The Windows Defender - as well as basically any other antivirus software - are more or less a black box with no way to know how and what they actually detect. I've seen some anti virus tools to simply blacklist programs downloaded from GitHub or ones that weren't signed by big companies. 
I couldn't find much about what kind of threat it detects besides that it apparently thinks ImHex is mining crypto currencies.

**Comment by Husamdababneh** [comment]
That's okay, It's on me, I didn't put a description in the first place, 

And yes, I'm with you on these points

**Comment by bialpio** [comment]
FYI, I'm seeing similar issue with portable zip and installer. Excerpt from defender's details below.

Defender claims to detect a thread "Backdoor:PHP/Dirtelti.CKB".

For portable zip:
```
file: C:\Users\bialp\Downloads\Windows.Portable.ZIP.zip->yara/official_rules/webshells/WShell_THOR_Webshells.yar
```

For installer:
```
file: C:\Users\bialp\Downloads\Windows.Installer.zip->ImHex-1.16.1-win64.msi->media1.cab->CM_FP_yara.official_rules.webshells.WShell_THOR_Webshells.yar
```

Not knowing much about ImHex's source code, looks like it's something related to yara's rules. Quick search points to the file that looks like it _may_ be originating from https://github.com/Yara-Rules/rules/blob/master/webshells/WShell_THOR_Webshells.yar. Seems that this is something that is fetched by `downloadImHexPatternsFiles()` cmake function, pulling it down from https://github.com/WerWolv/ImHex-Patterns.git repo (indirectly, there is a git submodule that points to the yara-rules repo).

Not sure if this is something actionable on your end (maybe offering yara rules as an optional download that can be done by the user manually instead of bundling it into the installer/zip could solve this), posting mostly as a heads-up for others in case I'm not the only one seeing this.

**Comment by Brynyard** [comment]
Just tried to compile this, and yes, this "virus" warning is still triggered.

Defender (et al.) has apparently detected this file in some other (actual) backdoor and blacklisted this file. As long as you decide to do nothing it will get randomly blocked/classified as a virus, so I would suggest you might want to change the file signature so this stops triggering (with some bad luck ImHex could also get tagged - talking from PE).

**Comment by WerWolv** [comment]
@Brynyard That's because when compiling ImHex, it will still download the ImHex-Patterns repo in full, including all Yara rules. The releases and nighly builds are clean however and shouldn't trigger a warning anymore

**Comment by Brynyard** [comment]
My point was that the compile triggers Windows Defender. It's up to you if you think this won't escalate, but as I mentioned, I have personal experience that this is not a good idea.
