### ISSUE TITLE
Boyer-Moore Relative Search

### ISSUE THREAD

**Issue by hansbonini** [WerWolv/ImHex#217]
Feature: Relative String Search based on Boyer Moore algorithm with possibility of create a .tbl on based results.

Like: https://github.com/rjricken/monkey-moore

**Comment by WerWolv** [comment]
Hi, could you please elaborate some more what exactly the search is going to find and what how should a .tbl file be generated out of this?
Improving search in general would be great though

**Comment by htdag** [comment]
Monkey-Moore: [https://www.romhacking.net/utilities/513/](https://www.romhacking.net/utilities/513/)

String search without knowing the charset in advance. 

`S*O*M*E` <=> 2 bytes per char (`*` = any <=> ` `)
`S***O***M***E` <=> 4 bytes per char
Keyword: `SOME` <=> 1 byte per char
`19 15 13 05` => match 
`18 14 12 04` => match
`16 12 10 02` => match
Because
```
19 - 15 = 18 - 14 = 16 - 12 = 'S' - 'O'
15 - 13 = 14 - 12 = 12 - 10 = 'O' - 'M'
13 - 05 = 12 - 04 = 10 - 02 = 'M' - 'E'
```
```
A  B  C  D  E  F  G  H  I  J  K  L  M  N  O  P  Q  R  S  T  U  V  W  X  Y  Z
            05                      13    15          19                     
```
=>
```
A  B  C  D  E  F  G  H  I  J  K  L  M  N  O  P  Q  R  S  T  U  V  W  X  Y  Z
01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
```
-> custom.tbl



What happens if the font also includes lowercase letters?
The Theory of Relative Searching: [https://www.romhacking.net/documents/742/](https://www.romhacking.net/documents/742/)

**Comment by hansbonini** [comment]
This is a relative search 100 times faster than the commonly used relative search, given the use of the Boyer Moore algorithm.
It's support all utf-8 characters, uppercase and lowercase. Wildcards are supported too.

Sample .tbl generated:
```
40=A
41=B
42=C
43=D
44=E
45=...
```

**Comment by WerWolv** [comment]
Boyer-Moore-Horspool is now being used for searching in the hex view
