### ISSUE TITLE
Feature request: Python plugin API

### ISSUE THREAD

**Issue by russkel** [WerWolv/ImHex#240]
I think we'd see a lot of cool plugins if they could be written in Python.
Perhaps the plugin API could be wrapped using pybind11?

**Comment by WerWolv** [comment]
The way the interface currently works, this is almost impossible. Most of the registries work by inheriting a class and then implementing a bunch of virtual functions. I don't think that's really possible to do with other languages.

I wanted to allow plugins written in Rust at some point but it also just doesn't play well with the current api.

Writing them in C++ is really the only option I can see. And I don't think it's a bad one since it's going to be a lot quicker than needing to call into python all the time

**Comment by russkel** [comment]
Fair enough. I haven't used ImHex or the plugin system in depth yet. Perhaps when I get around to it I could write a plugin which itself is the python API to expose a subset of the functionality.
