### ISSUE TITLE
Separate windows use up more and more RAM

### ISSUE THREAD

**Issue by PhoenixBound** [WerWolv/ImHex#266]
I just installed ImHex 1.8.1 and got it to work today on a Windows 10 computer, but I ran into this issue.

* Launch ImHex and open a file. (I opened an 8 MiB GBA rom.)
* Make the hex editor view docked to the parent window, if it isn't already. The RAM usage should be relatively stable and well below 150 MB.
* Click "View --> Disassembler View" to open a new view. Make sure it's its own window that can be moved around on the screen.
* (At this point, the RAM usage appears to increase by 30-40 MB every time the number updates in the status bar of the parent window. Task Manager also shows the memory rising rapidly.)
* Close the disassembler window that was opened with the [X], or dock it back to the parent window (or, if the window's been hidden behind other open programs, disable it from the View menu of the parent window). All of that extra memory will be freed, and ImHex will slowly adjust its display to the correct number.
* Undock the hex editor view, and watch it start growing again.

I tried doing a clean installation of ImHex, but the issue persisted.

**Comment by WerWolv** [comment]
Hi
I'm not sure I completely understand you correctly but I'll still try to answer. 

I just opened a 2.4GiB file which caused the memory usage of ImHex to increase by about 4MiB. Afterwards undocking a window (dragging it out of ImHex) indeed does increase the RAM usage by about 7MB once for me per Window. This almost definitely has nothing to do with ImHex but with how ImGui handles creation of those windows. It basically needs to create a new window through GLFW, create a new viewport and OpenGL context. I assume that's what takes up all that memory but there's not really anything I can do about that, it would need to be fixed in ImGui.

However, since most computers nowadays have 8GiB of RAM or more anyways, I don't really consider this as a big issue. It's not a memory leak, it's simply normal memory usage.

**Comment by PhoenixBound** [comment]
Um, I guess I didn't explain it very well. The RAM usage keeps increasing over time (~30-40 MB every two seconds), and very quickly, at least on my end.

I start with about 80 MB of total RAM usage. After opening the separate window and waiting for 5 minutes or so, it's gotten up to 3.87 GB, and it's still allocating more memory.

**Comment by WerWolv** [comment]
That's very weird. Does the task manager say the same thing?

I'm on a bit never dev version right now where it definitely didn't happen for me. Can you try one of the nightlies linked in the readme and see if it's fixed there for you?

**Comment by PhoenixBound** [comment]
Tried the nightly, and it seems like the same thing is happening.

Task Manager also shows it growing. The numbers don't match up 100% (though I guess maybe that could be attributed to Windows showing MiB instead of MB or something)
![image](https://user-images.githubusercontent.com/13182187/125146894-fcea0c00-e0ed-11eb-8038-dd635587cd8c.png)
