### ISSUE TITLE
[Feature] Modifiable disassembly

### ISSUE THREAD

**Issue by MarioPossamato** [WerWolv/ImHex#312]
### What feature would you like to see?

Don't know if this has already been implemented or not (wasn't able to find any information on it), but it would be very handy to be able to modify the disassembly in the Disassembler widget.

### How will this feature be useful to you and others?

It would make it much easier to modify an binary's assembly.

### 

- [ ] I can provide PoC for that feature or am willing to work on it myself and submit a PR

**Comment by WerWolv** [comment]
Hi!
That would absolutely be a cool feature. Problem is, since currently I'm using capstone for disassembling, it would require linking to e.g Keystone (and with that to LLVM) as an assembler which would be quite a lot of extra code and dependencies for something small like that. 
I think if I happen to need an assembler for more than just that, I'd consider adding it.

**Comment by MarioPossamato** [comment]
Also, it would be nice to select a region and have the option (in the Hex editor's context menu) to load it into the Disassembler widget.

**Comment by WerWolv** [comment]
You can somewhat do that by enabling the "Match Selection" option in the Disassembly view. Then you can just select any region in the hex editor and click "Disassemble" in the Disassembly view to disassemble those bytes

**Comment by MarioPossamato** [comment]
Ah, I see; nice! :)  Thank you!
