### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by thanksmia** [WerWolv/ImHex#383]
### What feature would you like to see?

8 zeros not 7 

### How will this feature be useful to you and others?

add a zero in the hex editor . 

A picture says more than a tousand words: https://bilderupload.org/bild/272e94529-7not8

https://bilderupload.org/image/272e94529-7not8.png

### Request Type

- [x] I can provide a PoC for this feature or am willing to work on it myself and submit a PR

**Comment by WerWolv** [comment]
Hi. The number of digits displayed in the address is dynamically adjusted depending on the size of the file. e.g If you have a file that's only 10 bytes long, its highest address can be displayed using only a single digit. If your file is 200 bytes long, then its highest address requires 2 digits to display so it does so. The reason you're seeing 7 digits being displayed instead of 8 is because your file's size is somewhere in-between 16 MB and 256 MB.

![image](https://user-images.githubusercontent.com/10835354/147133852-ab3e1db5-37c6-4dac-a2ca-9cf73394cbcf.png)
![image](https://user-images.githubusercontent.com/10835354/147133902-55a9f577-1ddd-48d6-b92f-46a2da47afa5.png)

I find this approach very reasonable as you just don't need to display that many digits (which take up space for no reason) if your file isn't that big in the first place and you don't want the number of digits grow when getting to a higher address since that will make the editor window jump around when scrolling.

**Comment by thanksmia** [comment]
Your assuption  of taking up space for no reasson is wrong. Imagine u have a hand with 5 fingers but u only programm it to "dynamically adjust"  that means if u only use 3 or 4 fingers then there will be no point in having 5 fingers. U need to set a standart every hex editor i know uses 8 digits , same with the 8 bits = 1 byte standart  there is no "dynamically adjust" them.   and int  takes 1 byte(8 bits ) they are not  "dynamically adjusted"
