### ISSUE TITLE
[Bug] All menu and button texts are displayed incorrectly

### ISSUE THREAD

**Issue by NickHarmer** [WerWolv/ImHex#413]
### Operating System

Windows

### What's the issue you encountered?

All the text for buttons and menu items appears as 'hex.builtin.xxx'

### How can the issue be reproduced?

There are no steps - it just happens (both portable and installed version)

### ImHex Version

1.14.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

Windows 11 / 48GB RAM / 2 x 2TB SSD / RTX 2080
4K display (btw it doesn't scale properly either)

And the FPS value is typically around 5 - which doesn't seem right

<img width="981" alt="image" src="https://user-images.githubusercontent.com/17000568/152501424-6adf089b-45d1-4905-a91e-c23f8627c9fe.png">

**Comment by NickHarmer** [comment]
Update: FPS is variable - sometimes it goes up to 60ish - so maybe that's not part of the issue

**Comment by WerWolv** [comment]
Hey
Try restarting ImHex once and if that doesn't work try restarting it as admin once.
Otherwise you might want to try one of the latest nightly releases, that should fix it too.

About the FPS, the number you set there is the maximum FPS allowed. ImHex automatically reduces the FPS to 5 if no events need to be processed (mouse movement, etc). This doesn't affect usage at all but reduces CPU and GPU usage a lot

**Comment by WerWolv** [comment]
This should be fixed
