### ISSUE TITLE
[Feature] Custom Encoding String Search

### ISSUE THREAD

**Issue by madsiur** [WerWolv/ImHex#436]
### What feature would you like to see?

I've been using ImHex for romhacking and really like the custom encoding feature. However I'd like to see a string search function for the custom encoding we use. Let's say we use a custom encoding covering all letters, here's a snippet of it:

81=b
8F=o
FF=[end]

Searching for the "bob[end]" string would be like searching in hex for 818F81FF.

Thanks again for your awesome work on ImHex!

### How will this feature be useful to you and others?

-Custom encoding string search is useful for reverse engineering old games and making fan translations.

### Request Type

- [ ] I can provide a PoC for this feature or am willing to work on it myself and submit a PR

**Comment by KillyMXI** [comment]
Would it make sense to write a pattern for that ROM structure?
I guess the knowledge about this encoding can be incorporated in the pattern and you will be able to see your strings. (Hmm. Being able to filter pattern data based on value column would be handy then.)
Or it might be too much to reverse engineer compared to the goal?

----

I think what's currently missing is a way to make a custom encoding/decoding in the data processor.
There are only a couple very specific decoders at the moment.

I guess a simple byte-to-byte mapping block (or a tool) won't be difficult but I suspect in reality more and more complex encodings will keep coming. Thinking about universal implementation though, not sure what would be the best way to approach it. This is actually where embedded scripting can come in handy...

There were some discussion in Discord about ideas that would allow to use patterns for complex data processing... (Another case with encoded data that requires a layer of indirection/preprocessing.)

And then there needs to be more ways to do something with the produced data in the data processor.
I'm not sure yet what "Write" block does - seems unsafe.
Display block for short buffers would be handy.
A block that can output to a file with given name would be handy (with a way to quick open that file).

A wild idea - A "lens" view parallel and in sync with the hex editor view that will contain the result of the encoding/decoding procedure. Albeit it seems to be difficult to implement, since encoded/decoded data size don't have to match.

**Comment by madsiur** [comment]
I have not looked at the pattern feature yet but if we can look for strings (or see a list of them) that way then it would probably accomplish the goal. Right now I know where most of the strings are in my ROM so I can just go to those offsets with a custom encoding loaded and see them. There are scenarios where you have some string figured out and a custom enconding reverse engineered but there a others non-located string in the ROM you could find by seaching for text you see in-game.

A hex editor that a lot of translators use is called Windhex, it has custom table support and the feature I first described but it has some downsides so I was hoping ImHex could be a good replacement for it.

**Comment by madsiur** [comment]
> Windhex - https://www.romhacking.net/utilities/291/ - this one?

Yeah that's the one. What I meant by "downsides" is that it lacks some basic things like copy-paste blocks with ctrl+c and paste-write/paste-insert hotkeys like HxD has.



> Searching in custom encodings shouldn't really be an issue to implement I think. The reason I held off with this originally was because of japanese and other unicode characters which would require special treatment.
> 
> I'm definitely up for trying to get it working now

Thanks a lot! :)
