### ISSUE TITLE
[Bug] Window shakes violently when resized

### ISSUE THREAD

**Issue by tilkinsc** [WerWolv/ImHex#456]
### Operating System

Windows

### What's the issue you encountered?

If you resize the window while a file is open the UI vibrates back and forth while resizing.

### How can the issue be reproduced?

Grab the title bar resize handle or the left window resize handle and well resize it

### ImHex Version

1.15.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occured.

**Comment by WerWolv** [comment]
Hey
This is a Windows thing and can't _really_ be fixed. Windows always draws the window and its decoration at the monitor refresh rate but the framebuffer / canvas we're drawing on is drawn at whatever framerate ImHex can pump out. These two are rarely the same. It becomes even more obvious when either you're using a monitor with a very high refresh rate or ImHex starts lagging.

This also happens to other applications, for example open a browser window and start resizing it from the top left corner. The same shaking and artifacts will appear there.

This issue has been open for a long time so sorry for the late reply. Closing this now though since we can't really do anything about it
