### ISSUE TITLE
[Bug] Crash on launch (due to logs)

### ISSUE THREAD

**Issue by darrellenns** [WerWolv/ImHex#462]
### Operating System

Linux

### What's the issue you encountered?

When launched with stdout redirected, imhex attempts to create a "logs" folder in the same directory as the imhex executable. If the executable is installed in a read-only location (such as the standard /usr/bin/ on linux), imhex crashes with the following error:

```
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot create directories: Permission denied [/usr/bin/logs]
```
This happens when launching via gnome applications menu, and can also be replicated in the cli by redirecting stdout.

I would suggest the following:
- Write logs to stdout regardless of whether it's a terminal or redirected elsewhere. In most cases, users will expect that redirecting stdout will not change the application behavior.
- If logs must be written to disk for some reason (not sure why this would be necessary for a hex editor), write them to a location in the user folder. Freedesktop might have some specification as to where this should be (maybe ~/.config/imhex/logs).
- If logging to disk is just for development/troubleshooting, consider making that a configuration option (defaulting to off).

### How can the issue be reproduced?

- Install imhex in /usr/bin (or another read-only location)
- Run `imhex > /dev/null`, or launch via gnome applications menu

### ImHex Version

1.16.2

### ImHex Build Type

- [X] Nightly or built from sources

**Comment by WerWolv** [comment]
I fixed the issue that led to the crash mentioned here.
Regarding your suggestions:

> Write logs to stdout regardless of whether it's a terminal or redirected elsewhere. In most cases, users will expect that redirecting stdout will not change the application behavior.

This is a bit annoying to do mostly because of Windows. On Linux it wouldn't be an issue

> If logs must be written to disk for some reason (not sure why this would be necessary for a hex editor), write them to a location in the user folder. Freedesktop might have some specification as to where this should be (maybe ~/.config/imhex/logs).

That's what ImHex is supposed to do. There's a few different places where ImHex tries to load stuff from and store data. One of those locations is right next to the application (when ImHex is used portably) and in `~/.local/imhex` for the other cases. ImHex just tires each path in order until it finds one that fits. The crash caused because I forgot to check for permissions in one place, if it didn't crash it would have placed the file under `~/.local/imhex/logs` next.

> If logging to disk is just for development/troubleshooting, consider making that a configuration option (defaulting to off).
Then I can remove the logging completely anyways. Often times when imhex crashes, the user doesn't exactly know what they did that caused the issue. If I then have to tell them to enable logging and somehow try to reproduce it, I'll most likely never get an actual useful result. I don't think they're particularly in the way or too big that they would become a problem. Other programs produce a lot more and more verbose logs.
