### ISSUE TITLE
[Bug] Process starts but interface(GUI) does not load in Windows 10

### ISSUE THREAD

**Issue by vastiditycoding** [WerWolv/ImHex#481]
### Operating System

Windows

### What's the issue you encountered?

Installed (ImHex-1.16.2-win64.msi) and tried to open it and nothing happened. I clicked it again and nothing. I opened Task manager and saw two ImHex processes running, ended/killed them and tried again...nothing.

I am running Windows 10 21H1 (OS Build 19043.1586) and also Kaspersky Total Security 21.3.10.391(h)

I checked the Application control settings and it was in "Low-Restricted" so I moved it over to "Trusted" ...tried to run ImHex again... nothing (process running with no GUI opened)

I opened a VM with Windows 10 21H1 installed and installed the same version of ImHex and when I went to run it... Windows Defender Smartscreen gave a warning. I gave it permission to run it and the interface actually loaded.

On my main non-VM machine... no Windows Defender warning popups up. It is disabled because Kaspersky Total Security is the active protection for OS.

I really want to use ImHex and do not know why the interface would not load, but the process does.

### How can the issue be reproduced?

Windows 10 21H1 with Kaspersky Total Security installed
Install application
Run application

### ImHex Version

1.16.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

Additional information about environment:

CPU: AMD Ryzen 3900X
Motherboard: MSI MPG X570 GAMING PLUS
RAM: 64GB
SSD: WD 1TB NVME drive
HDD: WD Black 10TB
GPU: MSI GeForce GTX 1050ti

**Comment by WerWolv** [comment]
Hey
Can you try the latest nightly build? [Installer](https://nightly.link/WerWolv/ImHex/workflows/build/master/Windows%20Installer.zip), [Portable](https://nightly.link/WerWolv/ImHex/workflows/build/master/Windows%20Portable%20ZIP.zip)

I had various reports of ImHex getting falsely flagged by a bunch of different anti-virus tools, probably because of some libraries I'm using (ImHex bundles both mbedTLS for crypto stuff and libyara for analyzing malware using Yara rules). If that still doesn't work, you probably have to add an exception for it to Kaspersky.

**Comment by vastiditycoding** [comment]
I tried the nightly build and disabled Kaspersky and it still did not work. So I restarted the system and now ImHex works (interface loads) even with Kaspersky running. Thanks for your help

**Comment by WerWolv** [comment]
Cool glad it works :)
