### ISSUE TITLE
[Bug] ImHex doesn't build against latest capstone build

### ISSUE THREAD

**Issue by the-eater** [WerWolv/ImHex#490]
### Operating System

Linux

### What's the issue you encountered?

While trying to build ImHex against the system capstone (which is currently the latest available, and as defined in the CMakeLists.txt, 4.0.2),

the build process fatally errors out on missed `CS_MODE_BPF_EXTENDED` and a few others

### How can the issue be reproduced?

building ImHex with `-DUSE_SYSTEM_CAPSTONE=1` with `capstone-devel` installed

### ImHex Version

1.16.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

From quick looking around, the case seems to be that instead of the denoted capstone version, a nightly is being used and meant to be built, however, it would be nice if that either was noted somewhere or if the capstone next functionality were behind a feature flag

**Comment by iTrooz** [comment]
@the-eater Could you tell which distribution you are on ? I'd say something like CentOS judging by the package name, but I'd like to be sure

**Comment by peterhoeg** [comment]
I can confirm that I'm seeing the same on NixOS with capstone 4.0.2 and ImHex 1.19.3

**Comment by WerWolv** [comment]
ImHex bundles its own version of Capstone for various different reasons. Partially because even 4.0.2 is not available on all platforms right now.

Please remove the `-DUSE_SYSTEM_CAPSTONE` argument from your build script and compile ImHex with the bundled one. This will most likely no longer be needed once Capstone 5.0 gets released.
