### ISSUE TITLE
[Bug] File switching gets confused when names are the same

### ISSUE THREAD

**Issue by sdasda7777** [WerWolv/ImHex#499]
### Operating System

Linux

### What's the issue you encountered?

File switching gets completely confused when opening either two files of the same name ('A/a.txt' and 'B/a.txt') - after switching to the one that was opened earlier, changing back is impossible. It also behaves pretty weirdly when opening project with the same name as a file that is opened - I assume one entry is for the project and the second one is for the file itself, but it would be nice to be able to distinguish those.

### How can the issue be reproduced?

Described above

### ImHex Version

1.17.0

### ImHex Build Type

- [X] Nightly or built from sources

**Comment by birorobi** [comment]
I can't find a solution, maybe because I'm in the IPRoyal group to use
other people and companies, every attempt by clicking and opening another
application my computer freezes and I have to refresh it and log in again
... for two months now.


pet, 22. tra 2022. u 18:43 sdasda7777 ***@***.***> napisao je:

**Comment by WerWolv** [comment]
This has been fixed with the new provider tabs
