### ISSUE TITLE
Flathub

### ISSUE THREAD

**Issue by Mailaender** [WerWolv/ImHex#511]
### What feature would you like to see?

I created a stable Flatpak from your nightly builds. https://github.com/flathub/flathub/pull/3195 Hope you don't mind.

### How will this feature be useful to you and others?

Get updated on the latest stable version with developer intended dependencies.

### Request Type

- [X] I can provide a PoC for this feature or am willing to work on it myself and submit a PR

**Comment by WerWolv** [comment]
Hey thanks a lot! I don't mind at all, however if possible I'd also like to have flatpak bundling be part of my CI so I can link to it from my nightly page.

I used to have one myself but it started to hang up the entire CI at some point and even when it was working, it basically trippled the build time for the Linux runner because it rebuilt ImHex _again_ from scratch so I removed it.

**Comment by Mailaender** [comment]
Flathub has beta channels, but the infrastructure is not really ready for nightly rebuilds. I also noted that the build is quite slow and due to the many bundled dependencies, the caching can't kick in like it does for other applications.

**Comment by barthalion** [comment]
It can be done with https://github.com/bilelmoussaoui/flatpak-github-actions and having a nightly manifest directly in your repo.

**Comment by WerWolv** [comment]
Looks like the flatpak is public now. Thanks a lot for the help!
