### ISSUE TITLE
Please add executable files for the 32 bit version. [Feature] 

### ISSUE THREAD

**Issue by UnlimitedChild** [WerWolv/ImHex#583]
### What feature would you like to see?

Hi!

Please add executable files for the 32 bit version. Thanks!

Regards!

### How will this feature be useful to you and others?

It will be possible to work on 32 bit systems.

### Request Type

- [ ] I can provide a PoC for this feature or am willing to work on it myself and submit a PR

**Comment by WerWolv** [comment]
Hey
This is not possible sadly because it would require TONS of adjustments everywhere. 
ImHex is a modern program that depends on many modern libraries and concepts. Even we were to get it running on 32 bit somehow, your computer will most likely be way too old and slow regardless so it wouldn't work well at all.
