### ISSUE TITLE
[Feature] Read only open files

### ISSUE THREAD

**Issue by Flamaros** [WerWolv/ImHex#592]
### What feature would you like to see?

I am working on a compiler and I generate .exe, actually ImHex lock files certainly because it open them with write flag. It would be interesting to have a read only mode or shared mode that allow outside modification of files. It should also detect the modification on offert the possibility to reload file.

### How will this feature be useful to you and others?

It will save a lot of clicks for developers who want to debug files with pretty complicated architecture like executable,....

### Request Type

- [ ] I can provide a PoC for this feature or am willing to work on it myself and submit a PR

**Comment by FutonGama** [comment]
Feels good, i have a problem when i try to edit a file. I mod Resident Evil 4 HD, so when i open the emleon file (this is the file for edit enemies and add new ones) and i go to the game, the game never loads because the file is opened on ImHex and i need to close from the program to the game loads, this don't happen on HxD for example.

**Comment by stonerhash** [comment]
Great idea this is a must

**Comment by miss-programgamer** [comment]
This just made me lose a bunch of time because I thought my code was doing something wrong to save files in a custom format when in actuality the file was just locked by ImHex, which I had open to verify the correctness of the format in the first place. At least adding an option to not lock files when they're opened would be a huge plus.

**Comment by WerWolv** [comment]
Okay this is the best I could come up with. 
ImHex now doesn't map files into its address space anymore but instead just uses regular file IO. This does come with quite a bit of a performance hit so I had to implement some buffering which isn't great but still better than constantly having to answer questions like this.

ImHex now also doesn't ever keep any write file handle around. It has its read handle and only briefly (tries to) open a write handle when actually writing data. This is okay since write operations are pretty rare and often happen in bigger batches anyways. This now actually allows you to have files open in multiple programs and all of them can write to the file at the same time without ImHex interfering.
