### ISSUE TITLE
[Bug] linux installation

### ISSUE THREAD

**Issue by monfora** [WerWolv/ImHex#594]
### Operating System

Linux

### What's the issue you encountered?

OS: Kali Linux (latest updates from repos)

sudo dpkg -i imhex-1.19.3.deb

Error:

dpkg-deb: error: archive 'imhex-1.19.3.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive imhex-1.19.3.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 imhex-1.19.3.deb

### How can the issue be reproduced?

sudo dpkg -i imhex-1.19.3.deb

### ImHex Version

1.19.3

### ImHex Build Type

- [ ] Nightly or built from sources

**Comment by WerWolv** [comment]
Hi
The .deb package targets Ubuntu 22 and not Debian (which Kali uses). I can probably make the build server use some other compression algorithm, however it will probably still not work because of missing dependencies.
I suggest you to instead use the AppImage release which should work on all Linux systems.
