### ISSUE TITLE
[Bug] UI tiny with hidpi screen

### ISSUE THREAD

**Issue by VK2BEA** [WerWolv/ImHex#598]
### Operating System

Linux

### What's the issue you encountered?

I have a hidpi setup and the UI is tiny.
I was not able to change the font size in the 'settings' tab (the slider is not responsive to the mouse)

### How can the issue be reproduced?

Use with hidpi display

### ImHex Version

1.19.3

### ImHex Build Type

- [X] Nightly or built from sources

### Additional context?

built from git on Fedora 36

(note also, I had to run 'ldconfig' after installation or libhex was not found) (should probably be done by the Makefile)

**Comment by WerWolv** [comment]
Hi
If automatic hidpi detection doesn't work for you, you can go under `Help -> Settings` and under `Interface`change the `Scaling` option from `Native` to `x2.0`. That should fix it for you.

The Font slider under the `Font` tab is only usable when a custom font has been selected. It's grayed out otherwise but you probably couldn't see that since it was so small.

As for ldconfig, I have never tested ImHex on Fedora myself but it works fine on Ubuntu and Arch Linux so it might be a Fedora specific thing.

**Comment by WerWolv** [comment]
I just corrected some issues with the hidpi detection so maybe it works better for you now after this commit

**Comment by VK2BEA** [comment]
OK, thanks .. I did not notice that setting.

**Comment by VK2BEA** [comment]
The fix solved the hidpi detection.

**Comment by WerWolv** [comment]
Great to hear! Thanks for testing :)
