### ISSUE TITLE
[Feature] not work after opened this file ?

### ISSUE THREAD

**Issue by imhunterand** [WerWolv/ImHex#634]
### What feature would you like to see?

**Hi!** its beatifull tool but can I use for my windows ?

### How will this feature be useful to you and others?

after i opened this, but not work at ``win10 64bit``

### Request Type

- [X] I can provide a PoC for this feature or am willing to work on it myself and submit a PR

**Comment by WerWolv** [comment]
Hi
Please use the bug report template instead of the feature request template next time.

As for your issue, please check the log files that have been created in `%localappdata%/imhex/logs`. Most likely GLFW failed to create the window because ImHex requires at least OpenGL 3.2 in the release (and OpenGL 3.0 in the nightly now). If you don't have a GPU and an older computer, it's possible that your system just doesn't support it.

**Comment by imhunterand** [comment]
```
[16:30:12] [INFO]  [main] Welcome to ImHex!
[16:30:14] [ERROR] [main] GLFW Error [65542] : WGL: The driver does not appear to support OpenGL
[16:30:14] [FATAL] [main] Failed to create GLFW window!
```

**Comment by WerWolv** [comment]
Yep, exactly. Your GPU simply doesn't support the required OpenGL version.
If you're using a VM, it's also possible that you didn't enable GPU passthrough properly

**Comment by imhunterand** [comment]
Thank you for clarifications!
Hope you will be happy nice days.

Regards

**Comment by agwego** [comment]
Same error with Windows 10 Enterprise VM on VBOX - 6.1 - Host OS Windows 10 Pro, AMD Ryzen Threadripper 2920X , Radeon RX 580

Tried various display driver settings in VBOX without success.

[11:23:46] [INFO]  [main] Welcome to ImHex!
[11:23:46] [ERROR] [main] GLFW Error [65542] : WGL: The driver does not appear to support OpenGL
[11:23:46] [FATAL] [main] Failed to create GLFW window!

**Comment by agwego** [comment]
There are not a lot of dials to change, just a turn on 3D-Acceleration checkbox, which doesn't work, c'est la vie
