### ISSUE TITLE
[Feature] ?

### ISSUE THREAD

**Issue by deprale** [WerWolv/ImHex#662]
### What feature would you like to see?

https://i.imgur.com/abKgFtK.gif

thanks, back to hxd

### How will this feature be useful to you and others?

will make people not go back to hxd.

### Request Type

- [ ] I can provide a PoC for this feature or am willing to work on it myself and submit a PR

**Comment by WerWolv** [comment]
What? I don't even understand what's wrong but feel free to go back to HxD lol

**Comment by manokara** [comment]
Snark aside, the bug is that when you click on the hex editor after the view changes to match the search, it behaves as if it was still in the previous position, seeking to `0x19F` instead of `0x59D0F`. Might be already fixed in master since there's been some hex editor fixes recently, but they didn't say which version of ImHex it was 🤷
