### ISSUE TITLE
[Bug] AppImage version fails to load remote data

### ISSUE THREAD

**Issue by joshas** [WerWolv/ImHex#680]
### Operating System

Linux

### What's the issue you encountered?

Starting program in terminal shows following error messages:
````
[ERROR] [libimhex] Net request failed with error 77: 'Problem with the SSL CA cert (path? access rights?)'
[ERROR] [main] Init task 'Checking for updates...' threw an exception: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
[ERROR] [libimhex] Net request failed with error 77: 'Problem with the SSL CA cert (path? access rights?)'
[ERROR] [libimhex] Net request failed with error 77: 'Problem with the SSL CA cert (path? access rights?)'
````
Update checking doesn't work. Clicking links in "Learn" and "Help" sections does nothing, results only in error message in terminal: `*** stack smashing detected ***: terminated`

### How can the issue be reproduced?

Download latest AppImage version, set program as executable and run program.

### ImHex Version

1.21.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

Fedora Linux 35 (Workstation Edition) 64-bit

**Comment by iTrooz** [comment]
Note : I could reproduce this on Fedora 35 but not Fedora 36
I will probably make more testing later

**Comment by iTrooz** [comment]
Update : this is caused because the path to the CA bundle is not a standard location. *sigh*
https://gitlab.com/probono/platformissues#certificates
https://curl.se/mail/lib-2022-05/0039.html

I'm going to investigate more, but it seems we have two ways to fix it :
- Patch gnutls to check all the paths : https://github.com/darealshinji/vlc-AppImage/issues/1#issuecomment-321041496
- Check the paths ourselves in the application (ImHex) : https://curl.se/mail/lib-2022-05/0039.html

I'm not sure what direction to take, I've asked on the #AppImage IRC channel if there was a recommended way to handle this

**Comment by iTrooz** [comment]
Well, we've gone another path
The AppImage now use a bundled version of the CA certificates
