### ISSUE TITLE
[Bug] Can not release file resources

### ISSUE THREAD

**Issue by yantul** [WerWolv/ImHex#692]
### Operating System

Windows

### What's the issue you encountered?

when I open a binary file, and i try to close file tab, and it seems to be closed normally, however, i can not delete that file, and i got error message that EBUSY, and i can found those file handler in resources monitor of windows task manager, and it exactly was inuse by imhex.

### How can the issue be reproduced?

open a binary file, and close, then delete that file.

### ImHex Version

1.21.2

### ImHex Build Type

- [X] Nightly or built from sources

### Additional context?

i am using windows11

**Comment by augustheart** [comment]
Too.I'm using win10. It is not a platform dependent bug. The bug caused by a virtual call in destructor.

in file "provider.cpp",they use a virtual method close all file handle at last stage.
```c++
Provider::~Provider() {
 for (auto &overlay : this->m_overlays)
            this->deleteOverlay(overlay);
        this->close();
}
```

Unfortuantely,in constructor or destructor, it cant guarantee we get correct function. 
I try to output some message in FileProvider
```c++
void FileProvider::close() {
    	OutputDebugStringA("fileprovider close");
        #if defined(OS_WINDOWS)
OutputDebugStringA("fileprovider close1");
            if (this->m_mappedFile != nullptr){
...
```
Use dgbview，we can sure the FileProvider::close() never called.The others provider shoud be the same problem.

**Comment by WerWolv** [comment]
Thanks a lot for investigating this! The latest commit should fix this issue now.

**Comment by yantul** [comment]
Thank you guys, I am looking forward to contributing to this project in the future continually.
