### ISSUE TITLE
[Feature] File browsers remembering last location independently

### ISSUE THREAD

**Issue by Grille** [WerWolv/ImHex#715]
### What feature would you like to see?

At the moment, the file-browsers seem to globally remember which file was last opened.
I would propose, that the file explorers for different file types (like project, pattern or file), remember their last location independently.

### How will this feature be useful to you and others?

e.g. I have the files I’m working on and the hex-patterns I use in different locations.

So every time I browse for an pattern, I have to navigate to that folder, and when I want to load another file I have to navigate back to that folder.

Its an small thing but, for me at least it would be an nice improvement, not having to do that anymore ^^

### Request Type

- [ ] I can provide a PoC for this feature or am willing to work on it myself and submit a PR

**Comment by WerWolv** [comment]
Hey
Since the file dialog is something that's entirely being handled by the Operating System, I don't think there's much I can do about this. Maybe it might be worth raising an issue on the [nativefiledialog-extended](https://github.com/btzy/nativefiledialog-extended) repository (the library I use for opening these dialogs). Maybe they know if it can be implemented.
