### ISSUE TITLE
hope add ubuntu install dependency script

### ISSUE THREAD

**Issue by ffashion** [WerWolv/ImHex#72]
thanks

**Comment by LegionMammal978** [comment]
For reference, these commands work on a fresh installation of 20.04.1 LTS:

    sudo apt install cmake git
    sudo apt install g++-10 libcapstone-dev libglfw3-dev libglm-dev libmagic-dev libssl-dev llvm nlohmann-json3-dev python3-dev
    git clone https://github.com/WerWolv/ImHex
    cd ImHex/build
    CXX=g++-10 cmake ..
    make -j

**Comment by umarcor** [comment]
@LegionMammal978, want to submit a PR for adding an script to https://github.com/WerWolv/ImHex/tree/master/dist?

**Comment by LegionMammal978** [comment]
@umarcor Actually, it seems that an equivalent script (`build-linux`) already exists in `.github/workflows/build_linux.yml`.

**Comment by umarcor** [comment]
@LegionMammal978, that's true. However, the content of `build_linux.yml` might change in the future, since the CI environment might change. However, users might want to use ImHex on Ubuntu 20.04, even after a different host is used for CI. Therefore, I would suggest:

- Create `get_deps_ubuntu20.sh` and add it to `dist`.
- In `build_linux.yml`, replace https://github.com/WerWolv/ImHex/blob/master/.github/workflows/build_linux.yml#L23-L36 with `sudo ./dist/get_deps_ubuntu20.sh`.

**Comment by Scoder12** [comment]
In case this helps someone else, didn't seem to work for me with pyenv activated, but in a root shell without pyenv it worked.

**Comment by umarcor** [comment]
I guess this can be closed since https://github.com/WerWolv/ImHex/blob/master/dist/get_deps_debian.sh is available now. Ref #79.

**Comment by ffashion** [comment]
> I guess this can be closed since https://github.com/WerWolv/ImHex/blob/master/dist/get_deps_debian.sh is available now. Ref #79.

yes,thanks
