### ISSUE TITLE
AppImage image releases

### ISSUE THREAD

**Issue by its0x08** [WerWolv/ImHex#81]
Hello,
Can we have a single file binary that we can just chmod and run?
Nothing worked for me on Kali (latest), which is sad to be honest..
Thanks

**Comment by Thog** [comment]
Never did an AppImage but it could be a nice thing to have I agree! ^^

**Comment by Tcll** [comment]
I'd like to back this
would like to be able to simply download and run ;)

**Comment by WerWolv** [comment]
PRs for this are absolutely welcome! I have no idea how they work (the same as with the dmg files on mac) which will cause them to become the same mess as the dmgs are right now

**Comment by Tcll** [comment]
I've never actually compiled one, but I kinda know what I'm supposed to do...
I'm not the best to rely on for this though... but I can absolutely inform ;)

there are 2 ways to build appimage binaries:

the first is just a simple pack all relative binaries into the local `/bin`, `/lib`, and other directories
but this doesn't exactly guarantee compatibility unless the binaries being packed are guaranteed portable...

thus the second and more complex method of building and packing a squashfs virtual environment comes into play
this method will induce migraines, but guarantees no reliance on kernel-specific libraries that would otherwise prevent the appimage from running.

I've never actually built a squashfs environment though and wouldn't know the first thing about doing so I'm afraid :(

**Comment by Tcll** [comment]
well, as a continuation of my previous post, since I've actually been looking into these things for some time...

I've recently been in contact with some of the unofficial packagers over at the minetest community, and it looks like they use a docker instance to get the squashfs environment following a template folder...
but it looks like the key part of appimage functionality is in static linking when compiling...

or in other words, the program must already be portable (capable of running from a flash drive on any distro)
like Blender for example...

at least this is the general vibe I'm getting from talking with numerous devs about portability...
uTox for example is looking to go full single-file executable instead of an appimage.

**Comment by eadmaster** [comment]
as alternative, [statically linking the Linux elf](https://www.systutorials.com/how-to-statically-link-c-and-c-programs-on-linux-with-gcc/) would also work for me, but it looks a tricky process.

**Comment by its0x08** [comment]
Thats what I meant by AppImage.. statically linking the ELF to make it portable.
Not dockerizing it!

**Comment by follower** [comment]
An AppImage would be great--I tried the Flatpak but it complained about needing `org.freedesktop.Platform/x86_64/20.08`...

(Which I *just* discovered I had had installed all along--but Flatpak _apparently_ thinks it's not necessary to _maybe_ look to see if it's installed under "user" rather than "system".

Oh, but it doesn't run afterward anyway due to `"$XDG_RUNTIME_DIR must have 0700 as permissions"` exception: https://git.sr.ht/~danyspin97/xdgpp/tree/master/item/xdg.hpp#L118 \*shrug\*)

Anyway, FWIW I did eventually get the pre-compiled version to (~~mostly~~[0]) run on an Ubuntu 18.04 LTS derived system via a convoluted method which I can't recommend but thought I'd at least mention...

[TODO: WIP]


[0] The application *was* crashing when I went to use a file dialog but apparently that was because I (somehow) overwrote the value of `XDG_DATA_DIRS` at some point. (Oh, it was probably when I ran one of the `xdg-*` binaries trying to figure what the current values were... lol. Guess I just needed `set | grep XDG`?)

Anyway, a helpful forum post "[File dialogs make applications crash if started from a terminal](https://bbs.archlinux.org/viewtopic.php?id=245985)" helped me solve that one, yay!

**Comment by Tcll** [comment]
just an update
I've looked into manually building an appimage with appimagetool and have to say, there's actually not much that needs to go into it
I was unsuccessful at getting it running though as my glibc version is 2.23 and the minimum required is 2.27
but here's as far as I was able to get on this machine:
![image](https://user-images.githubusercontent.com/773959/140817424-cb9d6618-4803-4e1e-b1af-5ec47c3fe72d.png)
![image](https://user-images.githubusercontent.com/773959/140817597-d8525edf-e808-4175-9e5b-60b2359583dc.png)

this may run on some other machines

**Comment by Tcll** [comment]
oh and also, just an FYI
it seems I was wrong about my previous efforts with docker
I've seen some friends go through heck and back just to build an appimage that didn't work
and even had to fix a docker mistake because the arch repo provided an AppRun binary that wasn't built properly

so you're actually better off building a static binary first and then optionally packing it into an appimage

the appimage is only a requirement if an external chroot is needed to find the local libs
(since linux's linker can't be expected to work properly and search both local and global paths)
^ it's not necessarily an ELF issue, though this is quite common.

**Comment by wardwouts** [comment]
I've created a docker setup in above PR (https://github.com/WerWolv/ImHex/pull/355) that drags all the needed libraries into the AppImage. It seems to work nicely.

**Comment by wardwouts** [comment]
> I've created a docker setup in above PR (#355) that drags all the needed libraries into the AppImage. It seems to work nicely.

Of course, 5 minutes later I start seeing this:
```
$ ./Imhex-v1.11.1-x86_64.AppImage
[INFO]  Welcome to ImHex!
imhex: /build/glfw3-kgzjId/glfw3-3.3.2/src/window.c:1085: glfwWaitEventsTimeout: Assertion `timeout >= 0.0' failed.
```
After starting and not actively using the ImHex AppImage for a while. I have no idea what causes this.

**Comment by presianbg** [comment]
Hi,

I've just download the AppImage from the `Releases` and looks like it crashes:
```
./imhex.AppImage 
Segmentation fault (core dumped)
```
Should it work on any linux distro ?
I have no problems with other AppImage applications.

**Comment by yazd** [comment]
This is the output I get when running the v1.12.0 AppImage on PopOS 21.10 x86_64.
```
Inconsistency detected by ld.so: dl-call-libc-early-init.c: 37: _dl_call_libc_early_init: Assertion `sym != NULL' failed!
```

**Comment by wardwouts** [comment]
I've extracted the image. Set my `LD_LIBRARY_PATH` to the relative `/usr/lib` dir from the extracted image and tried to run imhex. This shows the same issue. When I take out the following 4 library files, for me it starts working:
- libc.so.6
- libdl.so.2
- libpthread.so.0
- libselinux.so.1

It is not working well though, but I've repackaged the result into a new AppImage. First off, it complains that the capstone library is not there:
```
$ ./ImHex-stripped.AppImage
[ERROR] dlopen failed: libcapstone.so.3: cannot open shared object file: No such file or directory
[INFO]  Welcome to ImHex!
```
Second, many items in the userinterface show up weirdly:
![ImHex-screenshot](https://user-images.githubusercontent.com/94644/146000819-5927ac77-9f19-487a-a764-b9012d0998c9.png)

If you want to test with this AppImage version, just to see how far it gets you:
[ImHex-stripped.AppImage.zip](https://github.com/WerWolv/ImHex/files/7711709/ImHex-stripped.AppImage.zip)

**Comment by WerWolv** [comment]
I think we need to exclude the C and C++ standard libraries as those may be distro specific.
Building the AppImage locally and running it works totally fine, just not the one generated from github.

The issue shown in the picture @wardwouts postet should be fixed now. That was a problem with the normal release too

**Comment by presianbg** [comment]
Hi,

The latest AppImage release do not start on my system.
It fails with:
`imhex: symbol lookup error: /tmp/.mount_imhex.cR4uIS/usr/lib/libgtk-3.so.0: undefined symbol: gdk_broadway_window_get_type` 
Any ideas ?
