### ISSUE TITLE
[Bug] Project files not portable

### ISSUE THREAD

**Issue by ssmid** [WerWolv/ImHex#827]
### Operating System

Linux

### What's the issue you encountered?

"Failed to load project!"

### How can the issue be reproduced?

- copy project folder to another machine
- open project file

### ImHex Version

1.25.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

FlatHub

### Additional context?

The issue might come from the project file containing absolute pathes. This makes it unsuitable for transfer, syncs and even git repositories.

**Comment by WerWolv** [comment]
We can of course switch to relative paths but then moving either the file or the project file individually will break the loading too. 
Another way would be to just bundle the file into the project file but then the projects get potentially really really big so that's not really a solution either. What do you propose?

**Comment by KillyMXI** [comment]
Another option:
store relative paths to local files and absolute paths to external files.

**Comment by wischi-chr** [comment]
IMHO it would by great to ask the user where the files are or provide a simple mechanism to repair the project when the path has changed. I often work with image files on external drives and when sometimes those drives are mounted to different letters.
