### ISSUE TITLE
[Question] MSVC compiler 

### ISSUE THREAD

**Issue by MakarenkoPavel** [WerWolv/ImHex#850]
Hi, will it be helpful to support MSVC compiler for ImHex?

**Comment by WerWolv** [comment]
Hi
I'm really against trying to make ImHex compatible with MSVC simply because there's basically no benefit in doing so. ImHex is cross platform and can easily be compiled using GCC and Clang on all major OSes without any issues. Trying to support MSVC here would require either a lot of compile time switches or prevent me from using new C++ features that may be available in GCC and Clang but not in MSVC yet. So it would just result in more work for me without any actual benefit.

**Comment by Brynyard** [comment]
Yeah, "cross platform", just like "you can pick any color - as long as it's black".

Just had a look, and made it compile and run fine with MSVC. It only requires one (as in int{1}) compiler flag switch, and the only C++ "features" you're "prevented" from using are mostly syntactic sugar from ancient GNU extensions (and these "features" are not on track to ever enter the C++ standard). The only actual missing feature is i128 support, that needs a lib (just plugged in abseil). There's a lot of potential to remove old cruft if you started using any of the more of the modern (actual) C++ features, like ranges, filesystem, modules (though then you'd need to switch to msvc since the support in gcc and clang is quite patchy), etc.

But the real problem is that the CMake config is... ehm.. let's just be diplomatic and call it a "hot mess". I'd recommend you read on how to write modern (ie: post 3.10) cmake scripts and look into using a proper package manager, we're in 2022 after all.

**Comment by WerWolv** [comment]
I simply don't see any reason to put in all that work for little to no benefit. What does MSVC bring over any other compiler available?
If you'd like to rewrite the entire build script, please be my guest. I'm happy to review any potential PRs. Personally I rather work on actually improving ImHex itself than messing with stuff neither I nor any user have any benfit from.

**Comment by iTrooz** [comment]
> Yeah, "cross platform", just like "you can pick any color - as long as it's black".

ImHex also works on Windows, so cross-platform is still true : https://github.com/WerWolv/ImHex/releases/download/v1.25.0/imhex-1.25.0-win64.msi

**Comment by Brynyard** [comment]
Clang tries it's best to emulate the warning, options and analysis level of GCC, so as a testing tool it's not very good (borderline useless in fact), so using another compiler (which pretty much just leaves msvc and icc) would've given you a lot more warnings and also shown you some of the errors and bugs you have in the code, but given how many there are already (warnings that is) and that you seem consider this "useless" I suppose there's not much of a point :P

Here's someone explaining it with more words (and in a video!):
https://www.youtube.com/watch?v=dSYFm65KcYo
Or just text (and lots of links):
https://github.com/cpp-best-practices/cppbestpractices/blob/master/02-Use_the_Tools_Available.md

To be honest, there's so much to fix with the original make scripts that I'm not sure what would be left. I can clean up the "patch" and make sure it runs on all platforms (win/win/Mac*msvc/gcc/clang), but considering how invasive it would be I considered it to be a low probability that you'd want to merge it, so for now I'll just leave it (just a couple of hours of work, and I learned about the interesting bits I was after).

@iTrooz I know, I was just making a joke at the limitations on the build chain.

**Comment by WerWolv** [comment]
ImHex is built using GCC on all platforms currently which works perfectly fine. Also all code is compiled using `-Wall -Wextra -Werror` which enables almost all available warnings and turns them into errors that would cause compilation to fail. So not sure where you're getting your warnings from? Also what kind of bugs are you talking about? If you've found any, please open a new issue so they can be fixed.

The main issue I have with MSVC is that I put in a lot of effort to be able to build ImHex using gcc on all platforms. Previously we were using GCC on Windows and Linux and Apple-Clang on macOS which lead to all sorts of annoying issues because Apple's compiler always was a few versions behind, threw warnings that were completely undebuggable without a mac and generally caused a lot of headaches. I don't want the same thing to happen again by trying to force yet another compiler again into the mix. There's just not a good reason for it besides you prefering MSVC over other compilers. Using GCC everywhere makes developing, maintaining and testing ImHex so much easier and nicer for me.

Please explain what exactly is bad about the current build script, I'm always happy to improve parts of it if there are better ways to do it. "It's bad, redo it in modern cmake" isn't very helpful.

**Comment by Brynyard** [comment]
For a starter, if you're getting a lot of errors when just switching compiler, it's in high time you try another compiler, because you're basically just ignoring all the warnings and errors GCC doesn't catch (ref the video and the links from Jason Turner). I'm currently working on a fairly large project, with lots of low level code, using pretty much bleeding edge C++ (currently capped at 20, but so is this project), targeting just about everything (Win/UWP/Lin/BSD/Mac/iOS/Web/And), and we don't really have much problems with what you're describing, so apologies if I fail to empathize :P

I suspect a lot of the issues you're having is because the make scripts are a bit "shaky":
 * The compiler flags are set quite haphazardly (both inconsistently and using different methods)
 * Dependencies are mixed, comes from various sources, use different mechanisms for adding/hacking them in and are not complete
 * Quite a few settings are OS sensitive and can/will easily change the build
 * Things like "allow-multiple-definition" and "export-all-symbols" are inherently buggy (long story) and therefore not recommended (unless, of course, you enjoy having hard to find bugs)

My point with the "redo it in modern cmake" is that it's way less complicated to scrap the current scripts and use a newer cmake that requires much less hacks and workarounds than trying to put more band aids on something resembling a mummy. As I mentioned, I redid it in a couple of hours, and what I mostly did was remove stuff. Not supporting more than one compiler (and build environment) might make it cozy for you, but it also a effective strategy for not getting input and/or help from others.

BTW: what do you mean with Apple-clang "threw warnings that were completely undebuggable"? Clang pretty much set the standard for well formed warnings and error message (so much so that the GCC team spent a considerable amount of effort copying it), and it is available on all platforms (we use it on Windows because it has good sanitizers etc), so what was so undebuggable?

**Comment by WerWolv** [comment]
The errors I was getting with Apple Clang was mostly related to it not supporting many newer features or implementing them slightly different so code I wrote on Windows or Linux wouldn't properly compile on macOS. And since I don't have a mac, debugging it was always a huge pain.
ImHex isn't capped at C++20, I'm a strong advocate of using features as soon as they become available. So there's various places where I'm using C++23 features as well. With all of this, please also keep in mind that I don't have a team like you do, for the most part I'm working alone on this project.

- Most dependencies just get loaded in using `find_package` / `pkg_search_module` depending on the way they advertise themselves on the system. Everything else that can't be installed using e.g a package manager gets loaded in as submodules. I don't think there's really a better way of doing this since I don't want to compile every single dependency by hand in the build process.

- Which settings are you talking about? If you mean the stuff in `build_helpers.cmake`, that's mostly about bundling and installing ImHex and that just needs different settings depending on how you're bundling it and what OS you're on.

- I was actually able to remove `--allow-multiple-definitions` now, thank you! `--export-all-symbols` on the other hand I can't remove, I need libimhex to export all its symbols on Windows (the way it does by default on Linux and MacOS too) otherwise I can't interact with most of the class members defined there from the rest of ImHex. And littering my code with like `__declspec(dllexport)` isn't really nice either.

If you already have a cleaned up and working build script, please make a PR! I'm happy to look at it and see if I can improve things further.

**Comment by Brynyard** [comment]
Except for a [[noreturn]] (which is really there to make GCC ignore an error), the entire codebase compiles with 20, so I'm uncertain what those advanced features you're using are (and this is what my comment was reflecting).

.pc files really only work on old Linux dependencies (it's pretty much a legacy feature), and adding dependencies through add_subdir(...) is not a great way to solve the rest (submodules are dependent on the vars you set above, and that they can affect the compilation of the rest of the project, but you knew that, right?), even if they had been complete (which they're currently not - some have to be fetched through system and don't specify versions). What is commonly known as "modern cmake" is to import all dependencies through modules (ie imported targets exposed in <name>-config packages), and only compile/include the parts of your own code/project as add_subdir/etc (much like rust, C#, etc).

Some flags are set using the global directory recursive vars like CMAKE_CXX_FLAGS (and a bit comically by a function that takes target as arg), some through properties (like POSITION_INDEPENDENT_CODE), sometimes through the global add_link_directory/compile_definition, and yet sometimes (though rarely) on the specific target_<etc> functions/properties.

And btw, regarding that  bundling, what's wrong with CMakeRC and a plain install(...)?

DLL's aren't really the same as .so/.dylib's, symbol resolution and encapsulation is very different and exporting all symbols in them is renown for being "not a great idea"(tm). There is this obscure and little known feature inherited from C called macros that is usually applied to solving this, but you can also provide .def files. This flag is also recursive, we just expose a couple of structs/classes. Besides, exposing the entire codebase as an "API" isn't usually what one would refer to as an "interface" :P
