### ISSUE TITLE
[Bug] Net request 'https://api.werwolv.net/imhex/store' failed with error 60: 'SSL peer certificate or SSH remote key was not OK'

### ISSUE THREAD

**Issue by KhazAkar** [WerWolv/ImHex#907]
### Operating System

Linux

### What's the issue you encountered?

I've set my company's proxy address, but I'm unable to use content store due to this:

[14:49:37] [ERROR] [libimhex] Net request 'https://api.werwolv.net/imhex/store' failed with error 7: 'Couldn't connect to server'
[14:50:06] [ERROR] [libimhex] Net request 'https://api.werwolv.net/imhex/store' failed with error 60: 'SSL peer certificate or SSH remote key was not OK'
[14:50:06] [INFO]  [libimhex] A custom proxy '[REDACTED]' is in use. Is it working correctly?

### How can the issue be reproduced?

1. Setup proxy with self-signed certificate
2. Add it to ImHex editor settings page, proxy tab
3. Try to use Contents Store tool

### ImHex Version

1.26.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Appimage, Flatpak and Windows portable zip version

### Additional context?

I'm behind corporate proxy, using VPN and stuff (remote work etc)

**Comment by KhazAkar** [comment]
Hm... weird thing is that I can use curl to enter this URL without any issue
![image](https://user-images.githubusercontent.com/12693890/214859836-12c05587-1ffd-4a30-9a48-ca4c6efc7bcc.png)

**Comment by WerWolv** [comment]
Does your proxy require a specific SSL certificate to work? We're bundling our own one because SSL wouldn't work on Windows or with the AppImage and Flatpak otherwise. No idea what else could cause it tbh. All I'm doing is setting this option here if a proxy is set before making a web requires: https://curl.se/libcurl/c/CURLOPT_PROXY.html

**Comment by KhazAkar** [comment]
For that I have no idea. Seems like it. What should I do to fix it then? Install using deb/rpm?

**Comment by WerWolv** [comment]
If the SSL cert is the issue then yes, that would fix it.
Worst case if nothing works, you can still manually download everything that's found in the content store from https://github.com/WerWolv/ImHex-Patterns

**Comment by KhazAkar** [comment]
Can't install .deb package since I have too old Ubuntu version on my PC, 20.04, not 22.04 :/
Will try with converting rpm to deb and go this way...

**Comment by KhazAkar** [comment]
@iTrooz yes, I get my company one instead of this what you presented.

**Comment by WerWolv** [comment]
Yeah that sounds to me like your company is intersecting all traffic that goes in and out of their network. They installed their SSL certificate on your machine as a new root certificate so they can just decrypt all traffic, analyze it and then encrypt/sign it again using their own certificate.

Since ImHex bundles its own certificate, it completely ignores whatever changes your company has made to your system and keeps on encrypting the traffic using My/Cloudflare's certificate. And that will probably lead to your companies network infostructure just rejecting the connection because they can't intercept it

**Comment by iTrooz** [comment]
The only solution I see right now would be to compile ImHex yourself with your company's CA bundled

A long-term solution for us could be to add some code to try to detect system CA bundle before falling back on the bundled one

**Comment by WerWolv** [comment]
You can now specify a custom CA cert by placing it under `%localappdata%/imhex/config/cacert.pam`
