### ISSUE TITLE
[Bug] Bookmarks move randomly in the list

### ISSUE THREAD

**Issue by enekochan** [WerWolv/ImHex#935]
### Operating System

MacOS

### What's the issue you encountered?

Bookmark list elements change order randomly when interacting with them.

### How can the issue be reproduced?

I'm still not sure because it looks like something random. Having a long list of bookmarks, if you toggle open the last one (making the list have a vertical scroll), move the scroll to the bottom and then toggle close the bookmark, that bookmark and another one (I think it is the one that the mouse pointer would point to when the toggle is closed) in the list will change places between them.

In this video the last element "Bookmark [0x4083E64 - 0x4083E69]" (in blue) changes places with "Section 0 Length" (in purple):

https://user-images.githubusercontent.com/1836845/218619951-22e201e9-2b04-48b9-b124-7aa6277255c0.mp4

### ImHex Version

1.27.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Release dmg file

**Comment by enekochan** [comment]
I think the position of the mouse when toggle closes has something to do with this.

**Comment by WerWolv** [comment]
Hey
I think this is an unfortunate side effect of being able to reorder closed bookmarks by dragging them around. When you click on it  to close it, the size of the view changes so the scrollbar isn't necessary anymore and it jumps up, dragging the bookmark with it because your mouse is still pressed.

Not sure what the best solution for this would be. Maybe just require Shift or Ctrl to be held down to move the bookmark?
