### ISSUE TITLE
[Bug] Multiple break statements in one struct, only last one will trigger

### ISSUE THREAD

**Issue by RigoLigoRLC** [WerWolv/ImHex#958]
### Operating System

Windows

### What's the issue you encountered?

If I have multiple break statements in one struct, only the last one will trigger. In this example, the first one does not do anything
![图片](https://user-images.githubusercontent.com/49363666/221737570-1aa71290-b49e-40ba-9a21-b8a18bd1d0db.png)

### How can the issue be reproduced?

![图片](https://user-images.githubusercontent.com/49363666/221738035-7b6d0d8b-c6ba-4dd7-be04-26dd2106f0b5.png)

```
#include <std/core.pat>

struct foo {
    u8 a;
    if(std::core::array_index() == 0) break;
    if(std::core::array_index() == 5) break;
    if(std::core::array_index() == 20) break;
};

foo bar[300] @ 0;
```

### ImHex Version

1.27.1

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

MSI

**Comment by ershov** [comment]
Same here with night builds. The order or type of conditions doesn't matter.

**Comment by paxcut** [comment]
The problem here is the you are forcing the array to have 300 elements by doing
```cpp
foo bar[300] @ 0;
```
Instead of that you need to leave the number of elements it the array unspecified so that the conditions are free to stop it when conditions aren't met.
```cpp
foo bar[] @ 0;
```
using this last statement produces a struct with only one a.

**Comment by ershov** [comment]
@paxcut Yeah the work-around with `else`'s looks ok

**Comment by paxcut** [comment]
well, technically speaking it is not a work-around. The conditions are mutually exclusive so that if one is true the others cannot be true and that in turn implies that the else is necessary.  

Whats causing the apparent bug is that just like a condition that evaluates to true causes a break to execute a condition that evaluates to false causes the breaking to become false. This may not sound intuitive because if condition is false then it just doesn't execute the block, but it is possible that the code that detects if a break has been issued could look back at the last condition that had a break in its block and decide depending on what its condition evaluated to. 

Since, unlike return, break will evaluate the entire struct to the end then it looks like only the last condition is in effect.

**Comment by ershov** [comment]
Since general concepts like `for` and `break` are used in patterns, they are expected to behave accordingly. Whenever you see a code like this

```
for (i = 0; i < 10; i++) {
  if (...some condition...) break;
  if (...another condition...) break;
}
```

you don't say that the loop limit of 10 and the break conditions are "mutually exclusive". The loop stops at whichever comes first. 

And no, it's not intuitive that break would not stop the loop for any reason. If you believe this is the right and consistent behavior, you should definitely document it and highlight. As well as `bar[]` producing only one element.

**Comment by paxcut** [comment]
The documentation for how arrays are created exists and clearly distinguishes the constant size arrays  from the non-constant size. bar[]; reads only one element in the case of the code posted. in other cases it will produce other sizes.  

When a constant value is used the array will have that many elements. the conditional sized arrays depends on the conditions and the location of break; return and continue statements to determine how many element will be placed in the array.

Don't quote c code to try to derive what the pattern language should do. Although is close to c++ in some cases it s not the same language.

**Comment by WerWolv** [comment]
This is absolutely a bug and not intended behaviour. 
The latest commit attempts to fix it now. The provided example works fine now but it's possible that there's more edge cases. Let me know if it still doesn't work in some cases

**Comment by paxcut** [comment]
I never intended to insinuate that there was no bug but apparently I did and for that I apologize. 

I think I clearly explained what the bug was and even gave a method to demonstrate that this was indeed the case. The code I posted was not intended as a workaround and I also made sure to explain that but the argument for the correctness of the posted code stands. There is no sense to continue to do if statements that cannot possibly be true. 

But the two issues (the existence of the bug and the correctness of the code) are separate things and they are being interpreted as if they are being used to convince others that no bug exists. Let me be clear about that. Not even indirectly I intended to be interpreted that way and I thought that I clearly stated what my opinion on the issue was . Since it looks like thats not the case based on the comments above I felt I needed to post this to clarify and explain myself..
