### ISSUE TITLE
[Feature] some misc enhances

### ISSUE THREAD

**Issue by viruscamp** [WerWolv/ImHex#986]
### What feature would you like to see?

1. Keep all the parsed data when an error was thrown.
2. Add commit number in nightly build, about dialog , filename, file info, or download url
3. docs for pattern lang are missing in website, please add back

### How will this feature be useful to you and others?

Provided.

### Request Type

- [ ] I can provide a PoC for this feature or am willing to work on it myself and submit a PR

**Comment by WerWolv** [comment]
Hey
1. This can partially be done by setting the `#pragma debug` setting in your pattern to enable debug mode. Due to how the pattern language works, this will only keep all patterns that have already been placed in memory though. If an error happens inside of a type while it's being constructed, it will not show up.
2. a36b4d65e3d39ff424dfce515a409abd037b875f fixed this now
3. I added a link to the main page of the ImHex docs
